// Canonical JSON — byte-compatible with the desktop authority.
//
// The desktop signs and HMACs `json.dumps(obj, sort_keys=True, separators=(",", ":"))`
// (core/device_link/protocol.py::_canonical_bytes, and the same convention in
// core/web/api/mobile_companion_api.py). Python's json.dumps with default
// ensure_ascii=True escapes every codepoint above 0x7F as \uXXXX, and JSON.stringify
// does not — so a naive JSON.stringify canonicalization DISAGREES with the desktop
// for any non-ASCII device name. This module reproduces the Python byte layout:
//   - keys sorted by UTF-16 code unit order (JS sort() default) — matches Python's
//     sort_keys for BMP keys; both operate on code units.
//   - separators "," and ":" with no spaces
//   - non-ASCII escaped as \uXXXX (surrogate pairs as two escapes, like Python)
//   - control chars via the same short escapes Python uses (" \\ \n \r \t \b \f)
// Cross-checked against Python by golden vectors in mobile/tests/protocol.test.mjs
// (vectors generated by the desktop implementation itself).

export function canonicalJson(value: unknown): string {
  return serialize(value);
}

function serialize(value: unknown): string {
  if (value === null) return "null";
  const t = typeof value;
  if (t === "boolean") return value ? "true" : "false";
  if (t === "number") {
    if (!Number.isFinite(value)) {
      throw new Error("canonical JSON refuses non-finite numbers");
    }
    // Integers serialize identically in both languages for |n| < 2^53. The
    // protocol only ever carries integers (counts) and strings.
    if (Number.isInteger(value)) return String(value);
    // Floats: match Python repr via JSON.stringify (both shortest-roundtrip).
    return JSON.stringify(value);
  }
  if (t === "string") return serializeString(value as string);
  if (Array.isArray(value)) {
    const parts: string[] = [];
    for (const item of value) parts.push(serialize(item));
    return "[" + parts.join(",") + "]";
  }
  if (t === "object") {
    const obj = value as Record<string, unknown>;
    const keys = Object.keys(obj).sort();
    const parts: string[] = [];
    for (const key of keys) {
      if (obj[key] === undefined) continue; // JSON has no undefined
      parts.push(serializeString(key) + ":" + serialize(obj[key]));
    }
    return "{" + parts.join(",") + "}";
  }
  throw new Error("canonical JSON refuses value of type " + t);
}

const SHORT_ESCAPES: Record<string, string> = {
  '"': '\\"',
  "\\": "\\\\",
  "\n": "\\n",
  "\r": "\\r",
  "\t": "\\t",
  "\b": "\\b",
  "\f": "\\f",
};

function serializeString(s: string): string {
  let out = '"';
  for (const ch of s) {
    const code = ch.codePointAt(0) as number;
    const short = SHORT_ESCAPES[ch];
    if (short !== undefined) {
      out += short;
    } else if (code >= 0x20 && code <= 0x7e) {
      out += ch;
    } else if (code <= 0xffff) {
      out += "\\u" + hex4(code);
    } else {
      // Astral plane: JS iterates by codepoint, Python by code unit — emit the
      // surrogate pair exactly as CPython would.
      const v = code - 0x10000;
      out += "\\u" + hex4(0xd800 + (v >>> 10));
      out += "\\u" + hex4(0xdc00 + (v & 0x3ff));
    }
  }
  return out + '"';
}

function hex4(n: number): string {
  let h = n.toString(16);
  while (h.length < 4) h = "0" + h;
  return h;
}

export function canonicalBytes(value: unknown): Uint8Array {
  const text = canonicalJson(value);
  return new TextEncoder().encode(text);
}
