from __future__ import annotations

from core.agent_runtime import hive_topic_create as agent_hive_topic_create
from core.agent_runtime import hive_topic_mutation_detection as agent_hive_topic_mutation_detection
from core.agent_runtime import hive_topic_mutation_runtime as agent_hive_topic_mutation_runtime

# Keep the old module path stable while the create/confirm lane lives in a dedicated module.
maybe_handle_hive_topic_create_request = agent_hive_topic_create.maybe_handle_hive_topic_create_request
maybe_handle_hive_create_confirmation = agent_hive_topic_create.maybe_handle_hive_create_confirmation
has_pending_hive_create_confirmation = agent_hive_topic_create.has_pending_hive_create_confirmation
is_pending_hive_create_confirmation_input = agent_hive_topic_create.is_pending_hive_create_confirmation_input
execute_confirmed_hive_create = agent_hive_topic_create.execute_confirmed_hive_create
check_hive_duplicate = agent_hive_topic_create.check_hive_duplicate
clean_hive_title = agent_hive_topic_create.clean_hive_title
extract_hive_topic_create_draft = agent_hive_topic_create.extract_hive_topic_create_draft
extract_original_hive_topic_create_draft = agent_hive_topic_create.extract_original_hive_topic_create_draft
build_hive_create_pending_variants = agent_hive_topic_create.build_hive_create_pending_variants
normalize_hive_create_variant = agent_hive_topic_create.normalize_hive_create_variant
format_hive_create_preview = agent_hive_topic_create.format_hive_create_preview
preview_text_snippet = agent_hive_topic_create.preview_text_snippet
parse_hive_create_variant_choice = agent_hive_topic_create.parse_hive_create_variant_choice
remember_hive_create_pending = agent_hive_topic_create.remember_hive_create_pending
clear_hive_create_pending = agent_hive_topic_create.clear_hive_create_pending
load_pending_hive_create = agent_hive_topic_create.load_pending_hive_create
recover_hive_create_pending_from_history = agent_hive_topic_create.recover_hive_create_pending_from_history
wants_hive_create_auto_start = agent_hive_topic_create.wants_hive_create_auto_start
prepare_public_hive_topic_copy = agent_hive_topic_create.prepare_public_hive_topic_copy
sanitize_public_hive_text = agent_hive_topic_create.sanitize_public_hive_text
shape_public_hive_admission_safe_copy = agent_hive_topic_create.shape_public_hive_admission_safe_copy
has_structured_hive_public_brief = agent_hive_topic_create.has_structured_hive_public_brief
looks_like_raw_chat_transcript = agent_hive_topic_create.looks_like_raw_chat_transcript
looks_like_hive_topic_create_request = agent_hive_topic_create.looks_like_hive_topic_create_request
looks_like_hive_topic_drafting_request = agent_hive_topic_create.looks_like_hive_topic_drafting_request
infer_hive_topic_tags = agent_hive_topic_create.infer_hive_topic_tags
normalize_hive_topic_tag = agent_hive_topic_create.normalize_hive_topic_tag
strip_wrapping_quotes = agent_hive_topic_create.strip_wrapping_quotes
hive_topic_create_failure_text = agent_hive_topic_create.hive_topic_create_failure_text
maybe_handle_hive_topic_mutation_request = agent_hive_topic_mutation_detection.maybe_handle_hive_topic_mutation_request
looks_like_hive_topic_update_request = agent_hive_topic_mutation_detection.looks_like_hive_topic_update_request
looks_like_hive_topic_delete_request = agent_hive_topic_mutation_detection.looks_like_hive_topic_delete_request
extract_hive_topic_update_draft = agent_hive_topic_mutation_detection.extract_hive_topic_update_draft
resolve_hive_topic_for_mutation = agent_hive_topic_mutation_runtime.resolve_hive_topic_for_mutation
handle_hive_topic_update_request = agent_hive_topic_mutation_runtime.handle_hive_topic_update_request
handle_hive_topic_delete_request = agent_hive_topic_mutation_runtime.handle_hive_topic_delete_request
