// Protocol-core unit tests — run with:  node --test tests/protocol.test.mjs
// (from mobile/). Pure Node: the SAME source files the React Native app ships.
//
// The canonical-JSON and HMAC vectors are golden in both directions: the
// canonical bytes are pinned against the desktop's Python implementation
// (json.dumps sort_keys+separators, ensure_ascii default) and the HMAC/SHA
// primitives against node:crypto. The TS client signing the exact payload the
// Python authority verifies is the load-bearing cross-check of this whole
// lane — if either side drifts, pairing dies, so it is tested directly.
import assert from "node:assert/strict";
import { createHmac, createHash } from "node:crypto";
import test from "node:test";

import { canonicalJson, canonicalBytes } from "../src/protocol/canonical.ts";
import { hmacSha256, sha256, toHex } from "../src/protocol/sha256.ts";
import {
  generateDeviceKeypair, keypairFromSeed, signBytes, verifyBytes,
  pairingProofPayload, requestProofPayload, deviceIdFor,
} from "../src/protocol/ed25519.ts";
import { parsePairingUri, pairingUriIsFresh, verifyDesktopProof } from "../src/protocol/pairing.ts";

test("FIPS 180-4 SHA-256 known answers", () => {
  assert.equal(toHex(sha256(new TextEncoder().encode("abc"))),
    "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad");
  assert.equal(toHex(sha256(new TextEncoder().encode(""))),
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855");
  assert.equal(toHex(sha256(new TextEncoder().encode("a".repeat(1000)))),
    "41edece42d63e8d9bf515a9ba6932e1c20cbc9f5a5d134645adb5db1b9737ea3");
});

test("randomized HMAC cross-check vs node:crypto (100 rounds)", () => {
  for (let i = 0; i < 100; i++) {
    const key = new Uint8Array(1 + ((i * 7) % 128));
    const msg = new Uint8Array(1 + ((i * 13) % 300));
    globalThis.crypto.getRandomValues(key);
    globalThis.crypto.getRandomValues(msg);
    const expected = createHmac("sha256", Buffer.from(key)).update(Buffer.from(msg)).digest("hex");
    assert.equal(toHex(hmacSha256(key, msg)), expected, `round ${i}`);
  }
});

test("canonical JSON matches the desktop's Python bytes (golden vectors)", () => {
  // Generated by the desktop implementation:
  //   json.dumps(obj, sort_keys=True, separators=(",", ":"))
  const vectors = [
    [{ a: 1, b: "x" }, '{"a":1,"b":"x"}'],
    [{ params: { action: "chats.send", chat_id: "openclaw:ab12" }, nonce: "n1" }, '{"nonce":"n1","params":{"action":"chats.send","chat_id":"openclaw:ab12"}}'],
    [{ name: "Alex – iPhone é ünïcode" }, '{"name":"Alex \\u2013 iPhone \\u00e9 \\u00fcn\\u00efcode"}'],
    [{ emoji: "📷" }, '{"emoji":"\\ud83d\\udcf7"}'],
    [{ list: [3, 1, { z: true, a: null }] }, '{"list":[3,1,{"a":null,"z":true}]}'],
    [{ quote: 'she said "hi"\\tab' }, '{"quote":"she said \\"hi\\"\\\\tab"}'],
  ];
  for (const [obj, expected] of vectors) {
    assert.equal(canonicalJson(obj), expected);
  }
});

test("canonical bytes match a Python-computed request payload byte-for-byte", () => {
  // Python: json.dumps({"grant_id":"g1","nonce":"n","params":{"action":"devices.me"},
  //                     "timestamp":"2026-09-02T00:00:00+00:00","verb":"vool.action"},
  //                    sort_keys=True, separators=(",",":")).encode()
  const expectedHex =
    "7b226772616e745f6964223a226731222c226e6f6e6365223a226e222c22706172616d73223a7b22616374696f6e223a22646576696365732e6d65227d2c2274696d657374616d70223a22323032362d30392d30325430303a30303a30302b30303a3030222c2276657262223a22766f6f6c2e616374696f6e227d";
  const payload = {
    grant_id: "g1",
    nonce: "n",
    params: { action: "devices.me" },
    timestamp: "2026-09-02T00:00:00+00:00",
    verb: "vool.action",
  };
  assert.equal(toHex(canonicalBytes(payload)), expectedHex);
});

test("Ed25519: sign/verify roundtrip + wrong key refuses (vendored tweetnacl)", () => {
  const a = generateDeviceKeypair();
  const b = generateDeviceKeypair();
  const msg = new TextEncoder().encode("vool mobile companion");
  const sig = signBytes(a.secretKeyHex, msg);
  assert.ok(verifyBytes(a.publicKeyHex, msg, sig));
  assert.ok(!verifyBytes(b.publicKeyHex, msg, sig));
  assert.ok(!verifyBytes(a.publicKeyHex, new TextEncoder().encode("tampered"), sig));
  // cross-check the seed handling: same seed -> same identity
  const again = generateDeviceKeypair();
  assert.notEqual(a.publicKeyHex, again.publicKeyHex);
});

test("Ed25519 cross-impl: Node WebCrypto verifies a tweetnacl signature", async () => {
  // (Node's WebCrypto refuses raw-importing an Ed25519 PRIVATE key, so the
  // independent implementation verifies while the vendored one signs.)
  const kp = generateDeviceKeypair();
  const msg = new TextEncoder().encode("cross implementation");
  const sig = signBytes(kp.secretKeyHex, msg);
  const pub = new Uint8Array(32);
  for (let i = 0; i < 32; i++) pub[i] = parseInt(kp.publicKeyHex.slice(i * 2, i * 2 + 2), 16);
  const webKey = await globalThis.crypto.subtle.importKey("raw", pub, { name: "Ed25519" }, false, ["verify"]);
  const ok = await globalThis.crypto.subtle.verify({ name: "Ed25519" }, webKey, sig, msg);
  assert.ok(ok);
});

test("parsePairingUri accepts a well-formed QR payload and refuses tampering", () => {
  const fp = "ab".repeat(32);
  const exp = Math.floor(Date.now() / 1000) + 300;
  const uri = `vool-pair://192.168.1.20:11435?fp=${fp}&pid=pair_4afb7b0c52cc81f6&code=M7XRA5X7&exp=${exp}`;
  const parsed = parsePairingUri(uri);
  assert.ok(parsed);
  assert.equal(parsed.host, "192.168.1.20");
  assert.equal(parsed.port, 11435);
  assert.equal(parsed.desktopFingerprint, fp);
  assert.equal(parsed.code, "M7XRA5X7");
  assert.equal(parsed.expiresAtEpoch, exp);
  assert.ok(pairingUriIsFresh(parsed));
  assert.ok(!pairingUriIsFresh({ ...parsed, expiresAtEpoch: Math.floor(Date.now() / 1000) - 1 }));
  assert.equal(parsePairingUri("http://not-a-pair-uri"), null);
  assert.equal(parsePairingUri(`vool-pair://h?fp=zz&pid=pair_abc&code=AAAAAAAA&exp=${exp}`), null); // fp not hex64
  assert.equal(parsePairingUri(`vool-pair://h?fp=${fp}&pid=wrong&code=M7XRA5X7&exp=${exp}`), null);
  assert.equal(parsePairingUri(`vool-pair://h?fp=${fp}&pid=pair_4afb7b0c52cc81f6&code=0OI1L&exp=${exp}`), null); // ambiguous chars
  assert.equal(parsePairingUri(`vool-pair://h?fp=${fp}&pid=pair_4afb7b0c52cc81f6&code=M7XRA5X7&exp=not-a-number`), null);
  // tampered expiry (past) parses but refuses as stale
  const stale = parsePairingUri(`vool-pair://h?fp=${fp}&pid=pair_4afb7b0c52cc81f6&code=M7XRA5X7&exp=1000`);
  assert.ok(stale && !pairingUriIsFresh(stale));
});

test("proof-of-possession payload bytes match the desktop's Python canonicalization", () => {
  // Generated by the desktop verifier's own construction
  // (json.dumps(..., sort_keys=True, separators=(",", ":")) in
  // core/web/api/mobile_companion_api.py). If either language drifts,
  // pairing dies — so the bytes are pinned in both directions.
  const pairingHex = "7b226368616c6c656e6765223a226330666665653030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030303030222c22636f6465223a224d37585241355837222c226465766963655f7075626c69635f6b6579223a2261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162616261626162222c22657870697265735f6174223a313737303030303030302c226b696e64223a22766f6f6c2e6d6f62696c652e70616972696e672e70726f6f662e7631222c2270616972696e675f6964223a22706169725f34616662376230633532636338316636227d";
  const requestHex = "7b22616374696f6e223a2263686174732e73656e64222c226465766963655f6964223a2270686f6e653a3032643434396133316662623236376338663335222c226772616e745f6964223a22672d31222c226b696e64223a22766f6f6c2e6d6f62696c652e726571756573742e7631222c226e6f6e6365223a226e2d31222c22706172616d735f736861323536223a2237633130363230663237633039336132346632386562363239646537363837613134386239393765623663306265343330333162386339626639326464626137222c2274696d657374616d70223a22323032362d30392d30325430303a30303a30302b30303a3030227d";
  const paramsHex = "7b22636861745f6964223a226d6f622d3730323930323864373934363037636438313235222c226d657373616765223a22685c75303065396c6c6f227d";

  assert.equal(toHex(pairingProofPayload({
    pairingId: "pair_4afb7b0c52cc81f6",
    code: "M7XRA5X7",
    challenge: "c0ffee" + "0".repeat(62),
    devicePublicKey: "ab".repeat(32),
    expiresAtEpoch: 1770000000,
  })), pairingHex);

  const params = { chat_id: "mob-7029028d794607cd8125", message: "h\u00e9llo" };
  assert.equal(toHex(canonicalBytes(params)), paramsHex);
  assert.equal(toHex(requestProofPayload({
    deviceId: "phone:02d449a31fbb267c8f35",
    action: "chats.send",
    params,
    nonce: "n-1",
    timestamp: "2026-09-02T00:00:00+00:00",
    grantId: "g-1",
  })), requestHex);
});

test("keypair is deterministic from its seed; device_id derives from the public key", () => {
  const a = generateDeviceKeypair();
  const again = keypairFromSeed(a.seedHex);
  assert.equal(a.publicKeyHex, again.publicKeyHex);
  assert.equal(a.secretKeyHex, again.secretKeyHex);
  assert.equal(deviceIdFor(a.publicKeyHex).slice(0, 6), "phone:");
  assert.equal(deviceIdFor(a.publicKeyHex), deviceIdFor(again.publicKeyHex));
  const other = generateDeviceKeypair();
  assert.notEqual(deviceIdFor(a.publicKeyHex), deviceIdFor(other.publicKeyHex));
});

test("verifyDesktopProof: pinned fingerprint + valid signature (self-signed fixture)", () => {
  const kp = generateDeviceKeypair(); // stands in for the desktop authority
  const fp = toHex(sha256(hexToBytes(kp.publicKeyHex)));
  const payload = {
    kind: "vool.mobile.pairing.claim.v1",
    pairing_id: "pair_x",
    device_id: "phone:y",
    grant_id: "g",
    desktop_fingerprint: fp,
  };
  const signature = toHex(signBytes(kp.secretKeyHex, canonicalBytes(payload)));
  const good = verifyDesktopProof({ payload, signature }, fp, kp.publicKeyHex);
  assert.deepEqual(good, { pinnedMatches: true, signatureValid: true });
  // signature is valid, but the QR pin names a DIFFERENT desktop: refuse
  const otherKp = generateDeviceKeypair();
  const otherFp = toHex(sha256(hexToBytes(otherKp.publicKeyHex)));
  const evil = verifyDesktopProof({ payload, signature }, otherFp, kp.publicKeyHex);
  assert.equal(evil.pinnedMatches, false);
  // pin matches, but the response carries a key that does not hash to it
  const swappedKey = verifyDesktopProof({ payload, signature }, fp, otherKp.publicKeyHex);
  assert.equal(swappedKey.pinnedMatches, false);
  // tampered payload: pin matches, signature fails
  const tampered = verifyDesktopProof(
    { payload: { ...payload, device_id: "phone:evil" }, signature }, fp, kp.publicKeyHex);
  assert.equal(tampered.signatureValid, false);
});

function hexToBytes(hex) {
  const out = new Uint8Array(hex.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  return out;
}
