"""A build on a pinned turn must WORK, and the files must come from the pinned model.

Both halves matter and they used to be traded against each other.

`builder/controller.py::build_ollama_generate_fn` posts straight to Ollama's `/api/chat` with the
runtime's LOCAL tag, so on a pinned turn every file a build wrote would have been generated by
`qwen3:8b` and attributed to whatever the operator selected. That was prevented by refusing the turn
outright in `_should_run_builder_controller`:

    if explicit_model_owns_semantic_turn(source_context):
        return False

Measured on the installed build, that refusal did not produce a refusal. The turn fell through to the
selected model's tool loop, the model did not call `workspace.write_file`, and

    i need <ws>/v5/median.py with a median function

came back "I couldn't map that cleanly to a real action" after 75.6s -- verbatim, with 0 files on
disk. Pinning a model meant you could not build.

So the substitution is now prevented where it happens rather than by refusing the feature:
`_run_model_build` asks `pinned_generation` for a generate_fn backed by the SELECTED provider. The
tests below drive that seam rather than asserting the shape of the source, because the failure this
guards against is a silent swap and a swap is only visible in which provider was actually called.
"""
from __future__ import annotations

from types import SimpleNamespace
from unittest import mock

import pytest

from core.agent_runtime.builder import controller as agent_builder_controller
from core.agent_runtime.builder import pinned_generation

PINNED = "nvidia/nemotron-3-ultra-550b-a55b:free"
LOCAL_TAG = "qwen3:8b"


@pytest.fixture(scope="module")
def agent():
    from apps.vool_agent import VoolAgent

    return VoolAgent(backend_name="test-backend", device="openclaw-test", persona_id="default")


def _context(*, pinned: bool, workspace: str = "/tmp/ws", model: str = PINNED) -> dict[str, object]:
    ctx: dict[str, object] = {
        "workspace": workspace,
        "workspace_root": workspace,
        "operating_mode": "auto",
        "surface": "api",
    }
    if pinned:
        ctx["requested_model"] = model
    return ctx


def _manifest() -> SimpleNamespace:
    return SimpleNamespace(provider_id="openrouter-byok:" + PINNED, model_name=PINNED)


class _Recorder:
    """Stands in for the build itself: calls generate_fn once and reports one file written."""

    def __init__(self, *, files: tuple[str, ...] = ("median.py",)) -> None:
        self.generated: list[str] = []
        self.files = files

    def __call__(self, *, request, target_rel, source_context, generate_fn, run_tool_fn, **kwargs):
        # `**kwargs` absorbs the prove-it fields (expected_test_outcome, subject_paths) that the
        # real signature grew. These tests are about WHICH MODEL wrote the files, not about the
        # test verdict, so they should not have to track every new build parameter.
        self.generated.append(generate_fn("write median.py"))
        return SimpleNamespace(
            target_dir=target_rel,
            files_written=list(self.files),
            files_skipped=[],
            file_lines={},
            tests_ran=False,
            tests_passed=False,
            fix_rounds=0,
            expected_test_outcome=str(kwargs.get("expected_test_outcome") or "unspecified"),
            subject_paths=tuple(kwargs.get("subject_paths") or ()),
            test_returncode=None,
            test_command="",
            proof_failed=False,
            test_output="",
            handled=True,
            error="",
            # The mutation-authority fields the real report carries. Kept in step deliberately:
            # `_run_model_build` puts them in the turn's change ledger, so a double that omits them
            # makes this file fail on a lane it does not test (see builder/mutation_scope.py).
            scope_kind="open",
            authorized_paths=(),
            paths_refused=[],
            commands_refused=[],
        )


def _run(agent, *, ctx, build_app_from_spec, invoke_manifest, manifest):
    """Drive `_run_model_build` with the model lane stubbed, and return its result dict."""
    task = SimpleNamespace(task_id="task-pinned-build")
    with (
        mock.patch.object(
            agent.memory_router, "_requested_model_manifest", return_value=manifest
        ),
        mock.patch.object(agent.memory_router, "_invoke_manifest", side_effect=invoke_manifest),
        mock.patch(
            "core.agent_runtime.builder.app_builder.build_app_from_spec",
            side_effect=build_app_from_spec,
        ),
        mock.patch(
            "core.agent_runtime.builder.app_builder.render_app_build_response",
            return_value="Built it.",
        ),
        # The LOCAL lane. Any call to it on a pinned turn is the exact bug this file exists for.
        mock.patch.object(
            agent_builder_controller,
            "build_ollama_generate_fn",
            side_effect=AssertionError("the local Ollama lane generated a PINNED build"),
        ),
    ):
        return agent_builder_controller._run_model_build(
            agent,
            task=task,
            effective_input="i need median.py with a median function",
            classification={"task_class": "system_design"},
            interpretation=None,
            session_id="pinned-build-test",
            source_context=ctx,
            target={"root_dir": "v5", "platform": "generic", "language": "python"},
            load_active_persona_fn=lambda *a, **k: None,
        )


# --------------------------------------------------------------------------------------
# (b) the files are generated by the model the operator selected
# --------------------------------------------------------------------------------------


def test_a_pinned_build_generates_through_the_pinned_provider(agent) -> None:
    calls: list[str] = []

    def invoke_manifest(*, manifest, request, output_mode, task, source_context):
        calls.append(str(manifest.model_name))
        return None, SimpleNamespace(output_text="def median(values): ..."), None

    recorder = _Recorder()
    result = _run(
        agent,
        ctx=_context(pinned=True),
        build_app_from_spec=recorder,
        invoke_manifest=invoke_manifest,
        manifest=_manifest(),
    )

    assert calls == [PINNED], f"the build generated on {calls!r}, not on the operator's model"
    assert recorder.generated == ["def median(values): ..."]
    assert LOCAL_TAG not in str(result.get("response") or "")


def test_the_pinned_request_survives_the_real_prompt_budget(agent) -> None:
    """The shape of the request, checked against the real gate that rejected it.

    Found live, not in review. The first pinned build reaching a provider failed on EVERY
    generation with `prompt_budget_exceeded: protected system prompt and current turn require 166
    tokens, but only 16384 are available` and `system_prompt_preserved: false`. 166 of 16384 is not
    a size problem: the request carried a pre-built `messages=[{"role": "user", ...}]`, so the
    protected system instructions were absent from the list and `core/prompt_budget.py` fails closed
    on that regardless of length. A mock provider cannot see this -- so the captured request is run
    through the real budget function here.
    """
    from adapters.openai_compatible_adapter import _request_messages_with_memory

    captured: list = []

    def invoke_manifest(*, manifest, request, output_mode, task, source_context):
        captured.append(request)
        return None, SimpleNamespace(output_text="def median(values): ..."), None

    _run(
        agent,
        ctx=_context(pinned=True),
        build_app_from_spec=_Recorder(),
        invoke_manifest=invoke_manifest,
        manifest=_manifest(),
    )

    assert captured, "no request ever reached the provider"
    messages = _request_messages_with_memory(
        captured[0],
        context_window=24576,
        output_reserve_tokens=8192,
    )
    assert any(str(m.get("role")) == "system" for m in messages), (
        "the builder's system instructions never reach the message list, so prompt_budget rejects "
        "every generation of the build"
    )


def test_a_pinned_build_states_which_model_wrote_the_files(agent) -> None:
    """Attribution is stated, never assumed -- the operator could not tell before."""

    def invoke_manifest(*, manifest, request, output_mode, task, source_context):
        return None, SimpleNamespace(output_text="def median(values): ..."), None

    result = _run(
        agent,
        ctx=_context(pinned=True),
        build_app_from_spec=_Recorder(),
        invoke_manifest=invoke_manifest,
        manifest=_manifest(),
    )

    assert PINNED in str(result.get("response") or "")
    assert "the model you selected" in str(result.get("response") or "")


# --------------------------------------------------------------------------------------
# (a) a build on a pinned turn WORKS -- the gate no longer refuses it
# --------------------------------------------------------------------------------------


@pytest.mark.parametrize(
    "request_text",
    [
        "build me a telegram bot",
        "create a cli tool for parsing logs",
        "scaffold a fastapi service in the workspace",
    ],
)
def test_the_builder_gate_admits_a_pinned_turn(agent, request_text: str) -> None:
    """Verbatim the requests that used to be refused. Pinned and unpinned must now agree."""

    classification = {"task_class": "system_design"}
    with mock.patch("core.policy_engine.get", return_value=True):
        unpinned = agent._should_run_builder_controller(
            effective_input=request_text,
            classification=classification,
            source_context=_context(pinned=False),
        )
        pinned = agent._should_run_builder_controller(
            effective_input=request_text,
            classification=classification,
            source_context=_context(pinned=True),
        )

    assert unpinned is True
    assert pinned is True, (
        f"{request_text!r} was refused with {PINNED} pinned; the operator gets "
        '"I couldn\'t map that cleanly to a real action" instead of a build'
    )


# --------------------------------------------------------------------------------------
# A pin that cannot be honoured is refused BY NAME, never silently substituted
# --------------------------------------------------------------------------------------


def test_an_unresolvable_pin_is_refused_by_name(agent) -> None:
    result = _run(
        agent,
        ctx=_context(pinned=True),
        build_app_from_spec=_Recorder(),
        invoke_manifest=lambda **k: (None, None, "unreachable"),
        manifest=None,
    )

    response = str(result.get("response") or "")
    assert PINNED in response, "a refusal that does not name the model is not actionable"
    assert "vool" in response.lower(), "the operator must be told which lane does work"
    assert result.get("route_reason") == "builder_pinned_model_unavailable"


def test_a_pinned_model_that_produces_nothing_says_so(agent) -> None:
    """0 files from the operator's own model must not read as a generic build failure."""

    class _Empty(_Recorder):
        def __init__(self) -> None:
            super().__init__(files=())

    result = _run(
        agent,
        ctx=_context(pinned=True),
        build_app_from_spec=_Empty(),
        invoke_manifest=lambda **k: (None, None, "paid_call_not_authorized_or_reserved"),
        manifest=_manifest(),
    )

    response = str(result.get("response") or "")
    assert PINNED in response
    assert "paid_call_not_authorized_or_reserved" in response
    assert result.get("route_reason") == "builder_pinned_model_produced_nothing"


def test_an_unpinned_build_still_uses_the_local_lane(agent) -> None:
    """The baseline. Nothing pinned means nothing to honour, and the local lane is correct."""

    assert pinned_generation.requested_model_id(_context(pinned=False)) == ""
    assert pinned_generation.requested_model_id({"requested_model": "vool"}) == ""
    assert pinned_generation.requested_model_id(_context(pinned=True)) == PINNED


# --------------------------------------------------------------------------------------
# A PAID pinned build dispatches under a real reservation from the monetary authority
# --------------------------------------------------------------------------------------

PINNED_PAID = "z-ai/glm-5.3-flash"


def _paid_manifest() -> SimpleNamespace:
    """A manifest the paid gate itself classifies as paid_cloud (explicit metadata wins)."""
    return SimpleNamespace(
        provider_id="openrouter-byok:" + PINNED_PAID,
        model_name=PINNED_PAID,
        metadata={"cost_class": "paid_cloud"},
    )


def _authorization() -> SimpleNamespace:
    return SimpleNamespace(
        model_call_id="model-call-paid-build-1",
        provider_id="openrouter-byok:" + PINNED_PAID,
    )


class _EmptyRecorder(_Recorder):
    def __init__(self) -> None:
        super().__init__(files=())


def test_a_paid_pinned_build_dispatches_under_a_reservation(agent) -> None:
    """The builder used to arrive at `_invoke_manifest` with no `authorized_paid_call`, so every
    generation of every pinned paid build refused with `paid_call_not_authorized_or_reserved`
    before any request was sent. The generation must now carry a reservation from the same
    authority the router's own pick lane uses."""
    authorization = _authorization()
    contexts: list[dict] = []

    def invoke_manifest(*, manifest, request, output_mode, task, source_context):
        contexts.append(dict(source_context))
        return None, SimpleNamespace(output_text="def main(): ..."), None

    recorder = _Recorder()
    with mock.patch(
        "core.paid_call_reservation.reserve_owner_pick_paid_call",
        return_value=authorization,
    ) as reserve:
        result = _run(
            agent,
            ctx=_context(pinned=True, model=PINNED_PAID),
            build_app_from_spec=recorder,
            invoke_manifest=invoke_manifest,
            manifest=_paid_manifest(),
        )

    assert recorder.generated == ["def main(): ..."], "the build did not generate on the pinned model"
    assert reserve.call_count == 1
    reserved_kwargs = reserve.call_args.kwargs
    assert reserved_kwargs["manifest"] is not None
    assert reserved_kwargs["call_role"] == "answer_generation"
    assert contexts and contexts[0].get("authorized_paid_call") is authorization
    assert contexts[0].get("model_call_role") == "answer_generation"
    assert PINNED_PAID in str(result.get("response") or "")
    assert result.get("success") is not False, "a dispatched build is not a failure"


def test_a_refused_paid_reservation_names_the_denial_and_contacts_no_provider(agent) -> None:
    """The caps' own refusal code reaches the operator, the provider is stated as not contacted,
    and the turn closes FAILED -- a refused build is not a completed one."""

    def invoke_manifest(**kwargs):  # pragma: no cover - the assertion is the point
        raise AssertionError("a refused reservation must never reach the provider")

    def denying(*, denial, **kwargs):
        denial["reason"] = "daily_spend_cap_exceeded"
        return None

    with mock.patch(
        "core.paid_call_reservation.reserve_owner_pick_paid_call",
        side_effect=denying,
    ):
        result = _run(
            agent,
            ctx=_context(pinned=True, model=PINNED_PAID),
            build_app_from_spec=_EmptyRecorder(),
            invoke_manifest=invoke_manifest,
            manifest=_paid_manifest(),
        )

    response = str(result.get("response") or "")
    assert PINNED_PAID in response
    assert "daily_spend_cap_exceeded" in response, "the refusal must name the authority's own code"
    assert "provider was not contacted" in response
    assert result.get("success") is False
    assert result.get("route_reason") == "builder_pinned_model_produced_nothing"
    refusal_details = dict((result.get("details") or {}).get("builder_pinned_refusal") or {})
    assert refusal_details.get("provider_contacted") is False


def test_the_pinned_refusal_copy_leaks_no_absolute_workspace_path(agent) -> None:
    """/Users/<who>/.../home/workspace is a personal machine path; the default chat copy keeps it
    out while the audit record retains the detail."""
    result = _run(
        agent,
        ctx=_context(pinned=True, workspace="/Users/someone/private/home/workspace"),
        build_app_from_spec=_EmptyRecorder(),
        invoke_manifest=lambda **k: (None, None, "unreachable"),
        manifest=_paid_manifest(),
    )

    response = str(result.get("response") or "")
    assert "/Users/someone" not in response
    assert "Nothing was written." in response


def test_an_escaping_invoke_exception_releases_the_reservation(agent) -> None:
    """A reservation whose invoke escaped the loop's typed handling must not stay standing
    against the caps."""
    authorization = _authorization()
    released: list[Any] = []

    def invoke_manifest(**kwargs):
        raise RuntimeError("adapter exploded before typed handling")

    with (
        mock.patch(
            "core.paid_call_reservation.reserve_owner_pick_paid_call",
            return_value=authorization,
        ),
        mock.patch(
            "core.paid_call_reservation.release_owner_pick_paid_call",
            side_effect=lambda auth, **kwargs: released.append(auth),
        ),
    ):
        result = _run(
            agent,
            ctx=_context(pinned=True, model=PINNED_PAID),
            build_app_from_spec=_EmptyRecorder(),
            invoke_manifest=invoke_manifest,
            manifest=_paid_manifest(),
        )

    assert released == [authorization], "the standing reservation was not handed back"
    assert "RuntimeError" in str(result.get("response") or "")
    assert result.get("success") is False


def test_a_free_pinned_manifest_reserves_nothing(agent) -> None:
    """A verified-free or local pin never consumes the paid cap: no reservation is attempted."""

    def invoke_manifest(*, manifest, request, output_mode, task, source_context):
        assert "authorized_paid_call" not in source_context
        return None, SimpleNamespace(output_text="x = 1"), None

    with mock.patch(
        "core.paid_call_reservation.reserve_owner_pick_paid_call",
        side_effect=AssertionError("a non-paid pinned build must not reserve"),
    ):
        result = _run(
            agent,
            ctx=_context(pinned=True),
            build_app_from_spec=_Recorder(),
            invoke_manifest=invoke_manifest,
            manifest=SimpleNamespace(
                provider_id="ollama-local",
                model_name=LOCAL_TAG,
                metadata={"cost_class": "free_local"},
                runtime_config={"base_url": "http://127.0.0.1:11434"},
                source_type="local_path",
                adapter_type="ollama",
            ),
        )

    assert result.get("route_reason") != "builder_pinned_model_produced_nothing"
