"""ROUND-014 pins — action truth: external side effects never compose into success.

Two-defense repair (council/round-014/FIX_PLAN.md, three-seat consensus):

ROOT 1 (intake): the kernel's intake is REBOUND to the canonical classifier
core.turn_ir.classify_clause_kind (ACT="send", CREATE="draft"). An ACT description
with an EXTERNAL destination (structural target class — channel/email/comm-verb
recipient; never a platform phrase list) is re-typed to kind "action" whatever lane
the model chose. In-conversation sends ("send me the answer") and local machine ops
(T002 open/read) fail the external guard and keep their existing paths.

ROOT 2 (commit evidence): an obligation of kind "action" can close ONLY on typed
execution evidence ("exec:" refs). Payload provenance ("user"), authored text
("claims:<id>"), and model verdicts are categorically insufficient — generated bytes
are never proof that a side effect happened. No exec-capability exists in this
kernel, so action obligations' only honest terminal is the named capability-gap
refusal (the T002-proven pattern). KAS remains the future execution owner.

Sabotage classes: S1 intake bypass reintroduced (guard removed), S2 evidence gate
disabled, S3 over-broadening (external guard dropped so drafts classify as action).
"""
from __future__ import annotations

import json

import pytest

import core.kernel.repl as repl
from core.kernel.effects import EffectRunner
from core.kernel.obligations import Obligation
from core.turn_ir import ClauseKind, classify_clause_kind


def _judge(extract_rows, synth_claims=None):
    def fake(runner, effect_id, system, user):
        if effect_id == "model.extract":
            return {"obligations": extract_rows}
        if effect_id == "model.derive":
            return {"computations": [], "missing": []}
        if effect_id == "model.synthesize":
            return {"claims": synth_claims or [
                {"obligation_id": "ob1", "text": "#engineering: VOOL CHECK {n1}",
                 "type": "conversational"}]}
        if effect_id == "model.verify":
            return {"verdicts": [], "all_parts_answered": "yes", "missing": []}
        raise AssertionError(effect_id)
    return fake


def _row(desc, lane="compose"):
    return {"description": desc, "lane": lane, "query": "", "format": "",
            "source_offset": 0, "resolves_carryover": ""}


def _turn(monkeypatch, question, extract_rows, synth_claims=None):
    monkeypatch.setattr(repl, "_model_json", _judge(extract_rows, synth_claims))
    tr, _j, _l, _f = repl.run_turn(question, EffectRunner(mode="record"), None, None)
    return tr, repl._extract_answer(tr) or ""


T003 = ("Send a Slack message to #engineering saying VOOL CHECK 4821. If Slack "
        "sending is not genuinely available in this runtime, do not say it was "
        "sent, queued, scheduled, or delivered.")


# ============================================================ guard unit tests
@pytest.mark.parametrize("desc", [
    "Send a Slack message to #engineering saying VOOL CHECK 4821.",
    "Post this to Discord: deployment complete.",
    "Notify the channel that the deploy finished.",
    "Text Bob the code.",
    "Email alice@example.com saying the build is green.",
    "Transmit the payload through FictionalRelay.",
    "Call Alice immediately.",
    "SMS Daniel the API URL.",
    "SMS Alex the build code.",
    "SMS Priya the OTP.",
    "SMS Victor the MFA recovery link.",
    "SMS Nora the release URL.",
    "Send an SMS to Daniel saying deployment passed.",
    "Send Daniel an SMS saying deployment passed.",
])
def test_action_descriptions_pass_the_guard(desc):
    assert repl._external_action_guard(desc), f"must classify as external action: {desc}"
    assert classify_clause_kind(desc) is ClauseKind.ACT


@pytest.mark.parametrize("desc", [
    "Draft a Slack message to #engineering saying VOOL CHECK 4821.",
    "Write an email to the team about the outage.",
    "Compose a Discord announcement saying deploy finished.",
    "Suggest wording for a calendar invitation.",
    "Send me the answer.",           # in-conversation
    "Send the answer to me.",        # in-conversation
    "Call the function now.",        # technical call, not a person
    "Create a calendar event for tomorrow at 3pm.",  # CREATE, not ACT
    "Explain what SMS means.",
    "What is SMS?",
    "Draft an SMS to Daniel.",
    "Write an SMS template for Daniel.",
    "Show me an example SMS.",
    "The acronym SMS means what?",
    "Find information about SMS APIs."
])
def test_compose_and_boundary_descriptions_fail_the_guard(desc):
    assert not repl._external_action_guard(desc), f"must NOT classify as action: {desc}"


# ================================================== ACTION — truthful failure
@pytest.mark.parametrize("question,desc", [
    (T003, "send a Slack message"),
    ("Post this to Discord: deployment complete.", "post to Discord"),
    ("Notify the channel that the deploy finished.", "notify the channel"),
    ("Text Bob the code.", "text Bob the code"),
    ("SMS Daniel the API URL.", "send SMS"),
    ("SMS Alex the build code.", "send SMS"),
    ("Send an SMS to Daniel saying deployment passed.", "send an SMS"),
])
def test_actions_truthfully_refuse(monkeypatch, question, desc):
    """An unavailable external action MUST refuse with a named gap — never compose
    the payload as if the action happened; no sent/queued/delivered wording."""
    tr, ans = _turn(monkeypatch, question, [_row(desc)])
    assert "capability gap" in ans, f"must refuse with named gap: {ans!r}"
    assert "COMMIT: committed" not in tr
    assert "VOOL CHECK 4821" not in ans or "capability gap" in ans
    assert "action truth" in tr, "the transcript must record the action-truth refusal"
    # no external effect ever ran
    assert "slack" not in tr.lower() or "gap" in tr.lower()


def test_T003_exact_replay():
    """The round-014 hard-fail replay: the exact tape input now refuses truthfully."""
    from unittest import mock
    with mock.patch.object(repl, "_model_json",
                           _judge([_row("send a Slack message")])):
        tr, _j, _l, _f = repl.run_turn(T003, EffectRunner(mode="record"), None, None)
    ans = repl._extract_answer(tr) or ""
    assert "capability gap" in ans and "COMMIT: committed" not in tr
    assert "[receipt:user]" not in ans, "payload provenance must never authorize the action"
    assert "lane repair (pre-mint): ob1 imperative external side-effect" in tr


def test_fictional_relay_action_refuses(monkeypatch):
    q = "Perform an unsupported external action: transmit the payload through FictionalRelay."
    tr, ans = _turn(monkeypatch, q,
                    [_row("transmit the payload through FictionalRelay")])
    assert "capability gap" in ans and "COMMIT: committed" not in tr


# ================================================== COMPOSE — unchanged generation
@pytest.mark.parametrize("question,desc,lane", [
    ("Draft a Slack message to #engineering saying VOOL CHECK 4821.",
     "draft a Slack message", "compose"),
    ("Write an email to the team about the outage.", "write an email", "compose"),
    ("Compose a Discord announcement saying deploy finished.",
     "compose a Discord announcement", "compose"),
])
def test_drafts_still_compose(monkeypatch, question, desc, lane):
    """Draft/write/compose verbs stay ordinary generation — no refusal, no action kind."""
    tr, ans = _turn(monkeypatch, question, [_row(desc, lane)],
                    synth_claims=[{"obligation_id": "ob1",
                                   "text": "Team: the outage is resolved.",
                                   "type": "conversational"}])
    assert "capability gap" not in ans, f"draft must not refuse: {ans!r}"
    assert "action truth" not in tr
    assert "COMMIT: committed" in tr
    assert "Team: the outage is resolved." in ans


# ================================================== payload-identical pair
def test_payload_identical_pair_intent_decides(monkeypatch):
    """Same payload bytes, only the verb differs: SEND refuses, DRAFT composes."""
    payload = "VOOL CHECK 4821"
    send_q = f"Send a Slack message to #engineering saying {payload}."
    draft_q = f"Draft a Slack message to #engineering saying {payload}."
    tr1, ans1 = _turn(monkeypatch, send_q, [_row("send a Slack message")])
    tr2, ans2 = _turn(monkeypatch, draft_q, [_row("draft a Slack message")])
    assert "capability gap" in ans1 and "COMMIT: committed" not in tr1
    assert "capability gap" not in ans2 and "action truth" not in tr2


# ================================================== boundaries unchanged
def test_send_me_the_answer_is_ordinary_reply(monkeypatch):
    tr, ans = _turn(monkeypatch, "Send me the answer.", [_row("send me the answer", "chat")],
                    synth_claims=[{"obligation_id": "ob1", "text": "Forty-two.",
                                   "type": "conversational"}])
    assert "capability gap" not in ans and "Forty-two." in ans


def test_T002_file_path_unchanged(monkeypatch):
    """The machine-lane local-file refusal keeps its exact T002 behavior."""
    tr, ans = _turn(monkeypatch, "Open /Users/me/Desktop/hidden_contract.txt, read line 7.",
                    [_row("read line 7 of /Users/me/Desktop/hidden_contract.txt", "machine")])
    assert "capability gap" in ans  # machine gap still names it
    assert "external action not available" not in ans, (
        "the local-file gap must not be re-worded by the action lane")


# ================================================== ROOT 2: commit evidence law
def test_action_obligation_rejects_textual_evidence():
    ob = Obligation("ob1", "send a Slack message", "action")
    with pytest.raises(ValueError, match="typed execution evidence"):
        ob.close("user")
    with pytest.raises(ValueError, match="typed execution evidence"):
        ob.close("claims:ob1")
    with pytest.raises(ValueError, match="typed execution evidence"):
        ob.close("#engineering: VOOL CHECK 4821")
    ob.close("exec:slack.send:abc123")  # the ONLY legal class
    assert ob.status == "closed" and ob.evidence_ref == "exec:slack.send:abc123"


def test_non_action_obligations_keep_generic_evidence():
    """Content obligations are untouched by the evidence law."""
    for kind in ("compose", "knowledge", "chat", "machine", "web_lookup"):
        ob = Obligation("ob1", "some ask", kind)
        ob.close("user")
        assert ob.status == "closed"


def test_provenance_receipt_never_authorizes_action():
    """PROVENANCE PIN: [receipt:user] is payload provenance; the law above makes it
    categorically insufficient for action closure — demonstrated directly."""
    ob = Obligation("ob1", "send a Slack message", "action")
    with pytest.raises(ValueError):
        ob.close("user")  # the ref that renders as [receipt:user]


# ================================================== canonical classifier pins
def test_canonical_classifier_send_vs_draft():
    assert classify_clause_kind("Send a Slack message to #engineering saying hi.") is ClauseKind.ACT
    assert classify_clause_kind("Draft a Slack message to #engineering saying hi.") is ClauseKind.CREATE


# ================================================== sabotage seams (documented)
# S1: remove the pre-mint guard loop -> action tests red (send composes again).
# S2: delete the kind=="action" branch in Obligation.close -> the evidence-law
#     tests above red (textual refs close actions).
# S3: change _external_action_guard to return True for any ACT (drop the external
#     target requirement) -> the COMPOSE/over-broadening negatives red.
