"""The desktop shortcut points at a real, valid VOOL icon (not a generic Windows glyph).

Guards the branded-icon wiring: the .ico asset is a valid multi-size PNG-in-ICO, the shortcut
script accepts and applies -IconPath, and the installer passes the asset path through.
"""
from __future__ import annotations

import importlib.util
import struct
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
ICO = REPO / "installer" / "assets" / "vool.ico"
STOP_ICO = REPO / "installer" / "assets" / "vool_stop.ico"
ICNS = REPO / "installer" / "assets" / "vool.icns"
STOP_ICNS = REPO / "installer" / "assets" / "vool_stop.icns"
PNG = REPO / "installer" / "assets" / "vool.png"
STOP_PNG = REPO / "installer" / "assets" / "vool_stop.png"
GEN = REPO / "installer" / "assets" / "generate_icon.py"
PS1 = REPO / "installer" / "create_desktop_shortcut.ps1"
BAT = REPO / "installer" / "install_vool.bat"
SH = REPO / "installer" / "install_vool.sh"


def _parse_ico(blob: bytes) -> list[tuple[int, int]]:
    """Return [(declared_size, byte_len)] for each entry, asserting each is a PNG in bounds."""
    reserved, kind, count = struct.unpack("<HHH", blob[:6])
    assert reserved == 0 and kind == 1 and count >= 1, "not an ICO directory"
    entries = []
    for i in range(count):
        w, _h, _, _, _planes, _bpp, size, off = struct.unpack("<BBBBHHII", blob[6 + i * 16:6 + i * 16 + 16])
        assert off + size <= len(blob), "entry overruns file"
        assert blob[off:off + 8] == b"\x89PNG\r\n\x1a\n", "entry is not a PNG payload"
        entries.append((w or 256, size))
    return entries


def test_ico_assets_are_valid_multisize_png_icos() -> None:
    for ico in (ICO, STOP_ICO):
        assert ico.exists(), f"{ico} is missing"
        sizes = [s for s, _ in _parse_ico(ico.read_bytes())]
        # Needs at least the common shell sizes so it stays crisp in the taskbar and on the desktop.
        assert {16, 32, 48} <= set(sizes), f"{ico.name} lacks small sizes: {sizes}"
        assert 256 in sizes, f"{ico.name} lacks a 256px entry"


def test_generator_reproduces_both_icos() -> None:
    spec = importlib.util.spec_from_file_location("vool_generate_icon", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    # Regenerated bytes parse, and the checked-in assets are that exact output (not stale).
    white = mod.build_ico()
    red = mod.build_ico(fg=mod.STOP_FG)
    _parse_ico(white)
    _parse_ico(red)
    assert white == ICO.read_bytes(), "vool.ico is stale -- re-run generate_icon.py"
    assert red == STOP_ICO.read_bytes(), "vool_stop.ico is stale -- re-run generate_icon.py"
    assert white != red, "stop icon must be visually distinct from the launch icon"


def test_shortcut_script_applies_icon_path_with_fallback() -> None:
    text = PS1.read_text(encoding="utf-8")
    assert "$IconPath" in text, "shortcut script does not accept -IconPath"
    assert 'IconLocation = "$IconPath,0"' in text, "shortcut does not use the provided icon"
    assert "shell32.dll,220" in text, "shortcut lost its fallback icon"


def test_installer_passes_both_branded_icons() -> None:
    text = BAT.read_text(encoding="utf-8", errors="replace")
    assert "-IconPath" in text, "installer does not pass -IconPath"
    assert r"assets\vool.ico" in text, "installer does not point at the launch .ico"
    assert r"assets\vool_stop.ico" in text, "installer does not point at the stop .ico"
    assert "Stop VOOL.lnk" in text, "installer does not create the Stop VOOL shortcut"


# --- macOS (.icns) + Linux (.png) branding parity --------------------------


def _parse_icns(blob: bytes, *, allow_native_payloads: bool = False) -> list[bytes]:
    """Return ICNS element types while validating the supported payload formats.

    The checked-in launch asset is a native Finder export and legitimately contains
    legacy ARGB and ``info`` elements alongside PNG slots.  The generated stop asset
    remains PNG-only, so callers must opt into those native payloads explicitly.
    """
    assert blob[:4] == b"icns", "not an ICNS container"
    assert struct.unpack(">I", blob[4:8])[0] == len(blob), "ICNS length header mismatch"
    off, types = 8, []
    while off < len(blob):
        ostype = blob[off:off + 4]
        length = struct.unpack(">I", blob[off + 4:off + 8])[0]
        assert length >= 8 and off + length <= len(blob), "element overruns file"
        payload = blob[off + 8:off + length]
        if payload.startswith(b"\x89PNG\r\n\x1a\n"):
            pass
        elif allow_native_payloads and ostype in {b"ic04", b"ic05"}:
            assert payload.startswith(b"ARGB"), f"{ostype!r} native payload is not ARGB"
        elif allow_native_payloads and ostype == b"info":
            assert payload, "native ICNS info payload is empty"
        else:
            raise AssertionError(f"{ostype!r} payload is not a supported PNG")
        types.append(ostype)
        off += length
    return types


def test_icns_assets_are_valid_supported_payloads() -> None:
    assert ICNS.exists(), f"{ICNS} is missing"
    launch_types = _parse_icns(ICNS.read_bytes(), allow_native_payloads=True)
    assert b"ic08" in launch_types and b"ic09" in launch_types, (
        f"{ICNS.name} lacks 256/512 slots: {launch_types}"
    )

    assert STOP_ICNS.exists(), f"{STOP_ICNS} is missing"
    stop_types = _parse_icns(STOP_ICNS.read_bytes())
    assert b"ic08" in stop_types and b"ic09" in stop_types, (
        f"{STOP_ICNS.name} lacks 256/512 slots: {stop_types}"
    )


def test_png_assets_are_valid_pngs() -> None:
    for png in (PNG, STOP_PNG):
        assert png.exists(), f"{png} is missing"
        assert png.read_bytes()[:8] == b"\x89PNG\r\n\x1a\n", f"{png.name} is not a PNG"


def test_generator_reproduces_icns_and_png() -> None:
    spec = importlib.util.spec_from_file_location("vool_generate_icon_mac", GEN)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    # The launch asset is an intentional native Finder export, so it is validated structurally
    # above rather than compared to the generator's generic fallback. The stop asset remains
    # generated and must stay byte-for-byte reproducible.
    assert mod.build_icns(fg=mod.STOP_FG) == STOP_ICNS.read_bytes(), "vool_stop.icns is stale"
    assert mod.build_png() == PNG.read_bytes(), "vool.png is stale -- re-run generate_icon.py"
    assert mod.build_png(fg=mod.STOP_FG) == STOP_PNG.read_bytes(), "vool_stop.png is stale"
    assert ICNS.read_bytes() != STOP_ICNS.read_bytes(), "stop .icns must differ from the launch .icns"


def test_unix_installer_wires_branded_icons(tmp_path: Path) -> None:
    text = SH.read_text(encoding="utf-8")
    # macOS: a branded .app bundle carrying the .icns as its CFBundleIconFile.
    assert "make_mac_app_bundle" in text, "installer does not build a macOS .app bundle"
    assert "CFBundleIconFile" in text, "app bundle does not set an icon file"
    assert "vool.icns" in text and "vool_stop.icns" in text, "installer does not use both .icns assets"
    assert "Stop VOOL.app" in text, "installer does not create a Stop VOOL app icon"
    # Linux: the REAL create_desktop_shortcut runs in a sandbox and the GENERATED .desktop
    # entries must reference the branded .png icons. The old literal greps (Icon=${assets_dir}/
    # vool.png) went stale when icon values started flowing through desktop_entry_value()
    # escaping — the wiring was never lost, but prose could no longer prove it.
    generated, project_root = _generate_desktop_entries(tmp_path)
    assets_dir = project_root / "installer" / "assets"  # the install root's own assets dir
    launch_entry = (generated / "applications" / "VOOL.desktop").read_text(encoding="utf-8")
    stop_entry = (generated / "applications" / "Stop_VOOL.desktop").read_text(encoding="utf-8")
    assert f"Icon={assets_dir}/vool.png" in launch_entry, launch_entry
    assert f"Icon={assets_dir}/vool_stop.png" in stop_entry, stop_entry
    desktop_copy = generated.parents[1] / "Desktop" / "VOOL.desktop"  # ${HOME}/Desktop copy
    assert desktop_copy.exists() and f"Icon={assets_dir}/vool.png" in desktop_copy.read_text(encoding="utf-8")


def _generate_desktop_entries(tmp_path: Path) -> Path:
    """Run the REAL create_desktop_shortcut for its Linux lane in a sandbox.

    The installer is sourced only up to its ``parse_args`` boundary (no execution), so the
    function definitions load with the repo's own text; the generated entries are written
    under the sandbox home and returned.
    """
    import os
    import subprocess

    sandbox = tmp_path / "desktop-sandbox"
    home = sandbox / "home"
    (home / "Desktop").mkdir(parents=True)
    project = sandbox / "project"
    project.mkdir()
    for name in ("Open_Chat.sh", "Stop_VOOL.sh"):
        (project / name).write_text("#!/usr/bin/env bash\nexit 0\n", encoding="utf-8")
    # The icon assets are resolved as ${PROJECT_ROOT}/installer/assets: mirror the real
    # subtree so the generated entries carry the repo's real asset paths.
    (project / "installer").mkdir()
    (project / "installer" / "assets").symlink_to(REPO / "installer" / "assets", target_is_directory=True)

    installer_src = SH.read_text(encoding="utf-8")
    cut = installer_src.rfind('\nparse_args "$@"')
    assert cut != -1, "installer parse_args boundary not found"
    functions = sandbox / "installer_functions.sh"
    functions.write_text(installer_src[:cut] + "\n", encoding="utf-8")

    harness = sandbox / "run_shortcuts.sh"
    harness.write_text(
        "#!/usr/bin/env bash\n"
        "set -uo pipefail\n"
        f'source "{functions}"\n'
        # The .desktop lane is what this file guards; drive it deterministically on any
        # host with the same boundary-double rule the main-flow harness uses (a function
        # double, never PATH shadowing).
        "uname() { printf 'Linux\\n'; }\n"
        f'HOME="{home}"\n'
        "export HOME\n"
        f'PROJECT_ROOT="{project}"\n'
        'VENV_DIR="${PROJECT_ROOT}/.venv"\n'
        'DESKTOP_SHORTCUT_PATH=""\n'
        "create_desktop_shortcut\n"
        'rc=$?\n'
        'printf "HARNESS_RC=%s\\n" "${rc}"\n'
        'exit "${rc}"\n',
        encoding="utf-8",
    )
    harness.chmod(0o755)
    done = subprocess.run(
        ["/usr/bin/env", "bash", str(harness)],
        env={"PATH": "/usr/bin:/bin", "HOME": str(home)},
        capture_output=True, text=True, timeout=60,
    )
    assert done.returncode == 0, f"create_desktop_shortcut failed: {done.stdout}\n{done.stderr}"
    generated = home / ".local" / "share"
    assert (generated / "applications" / "VOOL.desktop").exists(), done.stderr
    return generated, project
