#!/usr/bin/env python3
"""Generate the pseudo-locale (qya-pseudo) from the canonical source registry.

The output is committed alongside the registry so adapters can be exercised
without regenerating. Deterministic by construction.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

from vool_localization.pseudo import pseudolocalize

REGISTRY = Path(__file__).resolve().parents[1] / "registry"


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--registry", type=Path, default=REGISTRY)
    args = ap.parse_args()

    src = json.loads((args.registry / "en.json").read_text(encoding="utf-8"))
    out = {
        "_meta": {
            "locale": "qya-pseudo",
            "label": "Pseudo-locale (generated stress fixture)",
            "generated": True,
            "human_reviewed": False,
            "generated_note": "GENERATED BY TOOLING — pseudo-localization of en.json for truncation/layout/encoding testing. Never ship to users.",
        },
        "strings": {k: pseudolocalize(v) for k, v in src["strings"].items()},
    }
    path = args.registry / "qya-pseudo.json"
    path.write_text(json.dumps(out, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {path} ({len(out['strings'])} keys)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
