"""Original bad->improved->elite prompt library across genres, plus module worked examples.

Generated from the doctrine-authoring workflow (original content, no copyrighted text). Usable as
few-shot references for the director and as fixtures for prompt-quality evals.
"""

from __future__ import annotations

EXAMPLES = [
    {
        "genre": "fantasy",
        "medium": "video",
        "user_idea": "a wizard on a mountain casting a spell, epic fantasy",
        "bad": "epic fantasy wizard casting a powerful spell on top of a mountain, highly detailed, 4k, 8k, ultra HD, masterpiece, trending on artstation, beautiful, stunning, intricate, hyperrealistic, magical, colorful glowing magic everywhere, cinematic lighting, best quality",
        "improved": "An old sorcerer in weathered grey wool robes stands on a windswept granite peak at dusk, raising a gnarled oak staff as pale blue arcane light gathers at its tip. Storm clouds mass behind him. Wide shot, low angle, 35mm, cold slate-and-teal palette with a single cyan magic accent, dramatic rim light from the sky behind him, drifting mist, painterly realism.",
        "elite": "Single subject: a weather-worn sorceress, mid-40s, silver-streaked black hair whipping in the wind, wearing layered charcoal wool and a rain-darkened leather mantle, standing at the crumbling edge of a granite cliff. She grips a cracked obsidian staff in both hands and drags it slowly upward; a lattice of pale cyan runes ignites in the air around the staff head, embers drifting down.\n\nComposition (clear hierarchy): FOREGROUND - wet black rock and a few storm-bent heather stalks trembling in gusts. MIDGROUND - the sorceress, three-quarter back view turning toward camera, sharp focus. BACKGROUND - a vast valley swallowed by an advancing wall of grey thunderheads, distant lightning threading the clouds, fading to atmospheric haze for depth.\n\nCamera: 35mm anamorphic look, eye-level, slow push-in from medium-wide to medium over 8 seconds with a subtle handheld sway; shallow depth so the runes bloom into soft oval bokeh.\n\nLighting: cold overcast key from the storm behind her (backlit rim on hair and staff for separation from the dark valley); the ONLY warm-ish fill is a faint cyan underlight thrown onto her jaw and hands by the runes; deep crushed shadow in the folds of the mantle. Palette: slate grey, gunmetal, bone, one accent of glacial cyan - everything else desaturated.\n\nMotion: hair and mantle ripple continuously in gusting wind; runes rotate slowly and pulse once as she completes the gesture; a fine sheet of rain drifts left to right; a single distant lightning flash on the final beat.\n\nAtmosphere: blowing mist, drifting embers, volumetric light raking through the rain. Mood: solemn, myth-weight, the calm before ruin. Photoreal, filmic grain, natural physics, one time of day, one weather system, sane hands and staff geometry.",
        "negative": "buzzword stacking (8k, masterpiece, trending on artstation), extra fingers, malformed hands, warped or bent staff, duplicate faces, floating disconnected limbs, plastic waxy skin, oversaturated neon, rainbow multicolor magic soup, cartoon glow, blown-out HDR halos, game UI, health bars, spell-icon overlays, watermark, text, logo, signature, modern clothing, wristwatch, zippers, shiny plastic armor with no wear, oversized pauldrons, symmetrical twin face, dead doll eyes, mannequin pose, cluttered frame with no focal subject, muddy flat low-contrast lighting, purple-nebula sky filler, motion blur smear, wrong-scale architecture"
    },
    {
        "genre": "sci_fi",
        "medium": "image",
        "user_idea": "a lonely astronaut looking up at a huge alien machine on another planet",
        "bad": "a cool astronaut looking at a big alien machine, sci-fi, futuristic, highly detailed, 8k, epic, cinematic, masterpiece, trending on artstation",
        "improved": "A lone astronaut in a white spacesuit standing before a massive alien machine on a desert planet, low camera angle for scale, dramatic side lighting, atmospheric dust haze, cinematic, detailed background, photorealistic.",
        "elite": "Wide establishing shot, photorealistic. SUBJECT: a single suited astronaut, tiny, standing at the base of a colossal derelict alien machine - a ribbed obsidian tower half-buried in pale dust, rising out of frame into haze. CAMERA: 24mm anamorphic lens, low angle tilted up the structure, camera locked; astronaut placed on the lower-left third with deep empty sky above to sell scale. SCENE HIERARCHY - Foreground: cracked ochre regolith, the astronaut's fresh boot-prints trailing in. Midground: the astronaut in a scuffed white hardshell suit, gold visor down, one gloved hand half-raised toward the tower. Background: the machine's flank climbing into dust haze, its surface etched with cold cyan glyph-channels that glow faintly from within. LIGHTING: twin suns - a large warm amber sun low on the horizon and a small blue-white sun higher up - casting two long crossing shadows across the dust; hard amber rim light down one edge of the suit, soft cyan bounce from the glyphs onto the gold visor. ATMOSPHERE: fine airborne dust, volumetric god-rays raking through it, thin ground fog pooling at the tower base. PALETTE: desaturated ochre-and-grey terrain against a single cold cyan tech accent. FINISH: 35mm film grain, high dynamic range with deep blacks, natural haze-based depth falloff, restrained contrast. MOOD: silent, ancient, overwhelming scale - awe over threat.",
        "negative": "floating or gibberish text, garbled fake-language UI overlays, extra limbs, warped or melted helmet, a photographer/camera reflected in the visor, duplicated astronaut, spotless factory-clean suit, plastic cartoon proportions, oversaturated rainbow neon, blown-out lens flares, heavy chromatic aberration, modern Earth brand logos, contradictory day-and-night lighting, mismatched shadow directions, cluttered HUD graphics over the whole frame, franchise-specific icons (energy swords, sandworms, badge insignia), low-detail smeared background, \"epic masterpiece 4k\" style tags baked into the render"
    },
    {
        "genre": "cyberpunk",
        "medium": "image",
        "user_idea": "a hacker girl standing in a rainy neon city at night",
        "bad": "cyberpunk city, neon lights, rain, girl, futuristic, blade runner style, highly detailed, 4k, 8k, trending on artstation, masterpiece, beautiful, cinematic lighting",
        "improved": "A lone woman in a soaked black raincoat stands on a wet neon-lit street in a futuristic megacity at night. Rain is falling, glowing signs reflect in the puddles at her feet, cyan and magenta lighting. Wide 35mm lens, shallow depth of field, moody and isolated atmosphere, photorealistic, cinematic.",
        "elite": "Medium-wide anamorphic photograph, 2.39:1, 35mm lens at eye level with a slight low angle. One clear subject: a lone transhuman courier, a woman in her mid-twenties, standing still and centered on a flooded pedestrian crossing in a rain-drenched megacity at 2 a.m. She wears a soaked matte-black techwear shell jacket with a translucent rain hood; a brushed-chrome cybernetic plate runs along her left jaw and catches magenta light; a hairline data-port scar sits behind her ear. Her weight is settled, chin slightly down, expression tired and wary. Foreground: rain streaking diagonally through the frame, out-of-focus red umbrella bokeh at the edges. Midground: the courier mirrored sharply in the black wet asphalt, one glowing cyan puddle under her boots. Background: a vertical canyon of stacked megastructures dissolving into fog, walls layered with holographic signage in short abstract glowing glyphs (no readable text), a colossal magenta advertisement of a slowly rotating face looming above, steam venting from street grates, tangled cables strung overhead. Lighting: cyan neon key from screen-left, a warm sodium-amber pool from a noodle stall at screen-right, hard magenta rim light separating her from the haze, deep crushed shadows. Volumetric god rays cut through drifting fog and rain. Palette limited to cyan, magenta and amber against near-black. Subtle film grain, gentle chromatic aberration on the highlights, shallow depth of field. Photorealistic, cinematic, quiet and tense.",
        "negative": "daylight, blue sky, sunshine, clean pristine surfaces, dry ground, rural or natural landscape, medieval, cheerful mood, pastel palette, oversaturated rainbow neon, garbled or misspelled sign text, floating gibberish characters, generic HUD overlay, video-game UI, plastic waxy skin, symmetrical pasted-on implants, flat even lighting, muddy grey shadows, low contrast, low resolution, blurry, out-of-focus subject, deformed hands, extra fingers, watermark, logo, signature, jpeg artifacts, lens dirt overload"
    },
    {
        "genre": "dark_ages",
        "medium": "video",
        "user_idea": "a viking longship coming out of the fog to raid at dawn",
        "bad": "epic viking warrior on a badass longship coming to raid, horned helmet, glowing eyes, highly detailed, 8k, ultra realistic, cinematic, dramatic god rays, teal and orange, trending on artstation, masterpiece, unreal engine",
        "improved": "A Norse longship approaching a rocky shore in morning fog, warriors in chainmail holding round wooden shields, carved dragon prow, grey overcast sky, cold desaturated color palette, cinematic natural lighting, wide shot, detailed weathered textures, moody atmosphere, no horns on helmets",
        "elite": "Single continuous wide shot, slow dolly push-in on a 100mm anamorphic lens compressing three receding layers of bog mist. A clinker-built oak longship - overlapping tarred strakes, hand-forged iron rivets bleeding rust, a carved dragon-head prow - glides out of dense grey fog toward a shingle beach at first light. Fifteen oarsmen in undyed oatmeal wool and riveted iron mail hauberks pull in slow unison; a lone steersman in a plain nasal helmet and single woad-blue cloak leans on the steering-oar at the stern. Their breath fogs in the cold air, oar-blades dripping, a black glassy wake spreading behind them. Lighting: flat overcast Nordic dawn at 7000K acting as a giant softbox, low contrast, no visible sun; the only warm accent is a covered 1900K brazier glow amidships. Desaturated earth palette - peat brown, bog black, oxblood, oatmeal wool - broken by the one woad-blue cloak. Grimed, wind-chapped faces; wet wool clinging; drizzle haze and faint peat smoke drifting through frame. Camera: 24fps, 180-degree shutter, T2.8, subtle handheld micro-jitter, slight underexposure to protect highlight detail in the fog. Naturalistic mud-and-iron realism, single clear subject, foreground prow / midground crew / background dissolving shoreline. No horned helmets, no polished metal, no sun flare, no fantasy elements.",
        "negative": "horned helmets, shiny plate armor, polished chrome metal, mirror-finish swords, teal and orange grade, saturated colors, dragons, fantasy creatures, glowing runes, magic effects, gothic cathedral, stained glass rose window, clean faces, perfect modern teeth, styled hair, plastic skin, HDR glow, lens flare, god rays, artstation, unreal engine render, neon, gunpowder, guns, cobblestone streets, brick, concrete, nylon rope, plastic, sunny blue sky, watermark, text, logo, extra fingers, warped hands, deformed anatomy"
    },
    {
        "genre": "ancient_history",
        "medium": "image",
        "user_idea": "a roman soldier standing on a wall at sunset",
        "bad": "epic roman warrior standing on castle wall at sunset, highly detailed, 8k, masterpiece, cinematic, trending on artstation, shiny gold armor, super muscular hero, white marble columns everywhere, dramatic epic lighting, ultra realistic, beautiful",
        "improved": "A Roman legionary of the Imperial period standing guard on the timber rampart of a frontier fort at sunset. He wears segmented iron lorica segmentata over a red wool tunic, an iron helmet with cheek guards, and rests his hands on a curved rectangular red scutum with a bronze boss; a pilum leans beside him. Warm low sunlight from the side, cool hills behind, dust in the air. Photorealistic, natural muted color, historically accurate Roman kit, one soldier, shallow depth of field.",
        "elite": "Medium-wide, low-angle portrait of a single Roman legionary of the mid-Imperial period (2nd century) standing watch on the earth-and-timber rampart of a northern frontier fort at dusk. He wears segmented iron lorica segmentata over a madder-red wool tunic, an Imperial-Gallic iron helmet with hinged cheek-guards, a gladius sheathed high on his right hip, and hobnailed caligae; both hands rest on the top rim of a curved rectangular scutum painted deep red with a bronze central boss and a yellow winged-lightning blazon. A pilum leans against the pointed timber palisade beside him. Behind and below: a defensive ditch, a squat timber watchtower, and cold blue hills dissolving into evening haze. Single light source - a low golden sun raking from camera-left - throws hard warm rim light along the helmet crest and shoulder plates and lets cool blue shadow fill the rest; fine dust and the soldier's visible breath catch the light. Shot on 85mm, shallow depth of field with the fort softly out of focus, near-eye-level-to-low angle for quiet authority. Surfaces: weathered iron with faint scratches and oil sheen, worn leather straps, hand-woven wool with slubs - no chrome, no gloss. Naturalistic muted earth palette, subtle film grain, photorealistic, period-authentic mid-Empire Roman military kit, one subject, clean scene hierarchy.",
        "negative": "stirrups, medieval castle, stone crenellations, plate armor, chainmail on a Roman, horned helmet, viking, katana, longsword, fantasy runes, glowing eyes, magic effects, pristine snow-white marble statues, spotless mirror-gold or chrome armor, oiled bodybuilder physique, orange-and-teal grade, neon or oversaturated color, HDR halos, plastic skin, gibberish text on banners, watermark, logo, wristwatch, zippers, modern stitching, camels in Bronze Age Greece, togas worn by soldiers, two competing subjects, extra fingers, cartoon, illustration filter"
    },
    {
        "genre": "modern_history",
        "medium": "image",
        "user_idea": "an old photo of a poor family during the great depression",
        "bad": "a sad poor family in the great depression, old vintage photo, black and white, very emotional, historical, cinematic, dramatic lighting, 4k, ultra detailed, masterpiece",
        "improved": "Black-and-white documentary photograph of a Depression-era farming family standing outside a weathered wooden cabin, around 1936. Worn patched clothing, tired unsmiling faces, dusty bare yard. Soft overcast daylight, deep focus, fine film grain, shot on large-format film in the style of 1930s FSA documentary photography.",
        "elite": "Documentary black-and-white photograph, American Dust Bowl, spring 1936. Single clear subject: a gaunt tenant-farmer mother in her early thirties, weathered sunburned face, deep-set eyes, chapped lips, holding a swaddled infant on one hip while two barefoot children in flour-sack dresses press against her skirt. Environmental portrait, framed medium-full at eye level, subject slightly off-center to the left. Setting: the sagging porch of an unpainted clapboard shack, cracked dry-earth yard, a hand-pump well and a rusted galvanized washtub behind them, one drought-bare cottonwood on the flat horizon. Wardrobe strictly period-accurate: patched cotton work dress, a man's oversized worn boots, hand-mended seams - no synthetic fabric, no printed logos, no zippers. Lighting: overcast midday, soft and near-directionless, faint catchlight in the eyes, open shade filling the shadows under the porch. Rendered as a 4x5 large-format silver-gelatin negative: edge-to-edge sharp focus at deep depth of field, fine even silver grain, full tonal range from a bright hazy sky to dense porch shadow, neutral-to-faint-sepia tone, slight natural film-edge vignette. Naturalist and unposed - no smiles, no direct eye contact with the camera, hands and posture showing fatigue. In the documentary tradition of Dorothea Lange and Walker Evans.",
        "negative": "modern clothing, synthetic fabric, nylon, plastic, wristwatch, modern eyeglass frames, zippers, velcro, sneakers, printed logos, brand names, smartphone, earbuds, post-period vehicles, HDR glow, digital over-sharpening, creamy shallow bokeh, 85mm portrait blur, studio softbox, ring light, lens flare, neon, saturated modern color cast, colorized look on a black-and-white request, perfect white teeth, flawless airbrushed skin, contemporary hairstyles, shaped modern eyebrows, manicured nails, visible modern tattoos, steampunk goggles and gears, reenactor stiffness with brand-new spotless costumes, cluttered anachronistic background, text, watermark, signature, extra fingers, distorted hands"
    },
    {
        "genre": "geopolitics",
        "medium": "video",
        "user_idea": "make a video explaining how much of the world's oil goes through the Strait of Hormuz",
        "bad": "A map of the world showing the Strait of Hormuz with oil and ships, geopolitics, super detailed, 4k, cinematic, epic tension between nations, glowing red arrows, war looming, dramatic.",
        "improved": "Top-down editorial map of the Persian Gulf and the Strait of Hormuz. Muted navy water, light warm-grey land, one cyan shipping-lane line passing through the strait, a few simple tanker icons along it. Clean sans-serif labels for Iran, Oman, and the U.A.E. A small stat in the corner reads \"~20% of global oil.\" Neutral infographic style, desaturated palette, 16:9.",
        "elite": "Single continuous shot, slow cinematic push-in, documentary-analytic tone. SUBJECT: a stylized 3D relief map of the Persian Gulf and the Strait of Hormuz seen from a high 25-degree satellite angle. Land is matte warm grey with faint topographic relief shading; water is deep desaturated navy with a subtle specular ripple. A single luminous cyan great-circle line traces the tanker shipping lane from the open Arabian Sea, threads through the narrow chokepoint between the coasts of Iran to the north and Oman to the south, then fans into the Gulf. Five simplified oil-tanker silhouettes drift slowly along the lane leaving faint wakes. Thin white graticule lines cross the frame; hairline dashed strokes mark contested maritime edges. Minimal on-frame text: three small-caps labels only - STRAIT OF HORMUZ, IRAN, OMAN - in clean off-white sans-serif. A restrained data panel lower-left holds ONE figure, \"~20% OF GLOBAL SEABORNE OIL,\" with a slim horizontal bar filled to one-fifth. LIGHTING: one soft key from upper right simulating a low sun, long gentle shadows off the coastal relief, faint atmospheric haze at the horizon, no lens flare. CAMERA: dead-locked, one steady 8-second dolly-in from wide strait context toward the chokepoint, constant velocity, no shake. PALETTE: navy, warm grey, one cyan accent, off-white type - desaturated, editorial, strictly neutral (no red/blue side-coding). A thin source-credit strip runs along the bottom edge. Photoreal-infographic hybrid, crisp, high detail, correct coastlines, legible undistorted labels. 16:9.",
        "negative": "propaganda coloring, red-vs-blue enemy coding, glowing red danger zones, explosions, missiles, mushroom clouds, soldiers, tanks, blood, waving national flags, chess pieces on a map, puppet strings, cartoon animal-nations (eagle/bear/dragon), doomsday clock, cracked splitting earth, warped or gibberish text, misspelled country names, distorted coastlines, invented borders, oversaturated neon, rainbow choropleth, lens flare, heavy film grain, Dutch tilt, motion blur streaks, crash zoom, cluttered dashboard, too many arrows, 3D beveled text, stock-photo handshake, sensational headline chyron, ominous vignette"
    },
    {
        "genre": "thriller",
        "medium": "video",
        "user_idea": "a guy running from someone at night in a city",
        "bad": "a scary chase scene at night, man running from a bad guy, super tense, ticking clock, dramatic cinematic lighting, 8k, ultra realistic, masterpiece, trending on artstation",
        "improved": "Night-time foot chase in a city alley. A man in a dark coat runs away from a hooded figure behind him. Wet streets reflecting streetlights, low-key lighting with strong shadows, shallow depth of field. Handheld camera following the runner, telephoto lens compressing the background. Cool blue and amber color grade, tense urgent atmosphere.",
        "elite": "Medium backward-tracking shot, telephoto ~85mm compression, low camera height. A lone man in a rain-soaked grey overcoat sprints toward the lens down a narrow industrial alley, clutching a hard-shell briefcase to his chest, snapping a glance back over his right shoulder. Twenty meters behind him a single silhouetted pursuer walks - never runs - closing the gap by sheer steady inertia. Environment: dead-end corridor between soot-black brick warehouses, overflowing dumpsters, a chain-link fence sealing the far end. Lighting: low-key, one sodium-vapor streetlamp throwing hard amber pools with deep black gaps between them; wet asphalt mirrors every light source; a distant blue security floodlight bleeds through thin fog to rim-light the runner's shoulders. Camera: handheld-style subtle instability, tracking backward just ahead of the runner; shallow depth of field, background soft and compressed; hold the pursuer in focus-falloff so he reads as a shape, not a face. Motion: hard rain, breath fogging, puddles bursting under each footfall, coat flaring; the pursuer stays deliberately unhurried. Color grade: teal shadows, sodium-amber highlights, crushed blacks, high contrast. Sound: close-mic'd labored breathing, footsteps slapping wet concrete, a distant repeating alarm ticking like a metronome, no music. 6-second shot, real-time pacing, ending the instant the runner hits the dead-end fence.",
        "negative": "flat even lighting, bright cheerful daylight, smiling or relaxed subject, calm neutral body language, clean dry streets, warm cozy tones, over-saturated colors, neon cyberpunk pink/blue wash, multiple competing focal points, crowd of bystanders, fully-lit clearly-revealed villain, cartoonish, plastic skin, lens-flare overload, two suns / contradictory shadow directions, motion blur smearing the subject's face, static posed portrait, text overlay, watermark, jump-scare face lunging at camera, glowing knife, red digital bomb countdown on screen"
    },
    {
        "genre": "horror",
        "medium": "video",
        "user_idea": "make a scary video of a haunted hospital with a ghost",
        "bad": "a scary haunted hospital at night, creepy ghost woman, glowing red eyes, blood everywhere, jump scare, horror, dark and spooky atmosphere, nightmare fuel, terrifying, ultra detailed, 8k, cinematic, trending on artstation",
        "improved": "An abandoned hospital corridor at night. Far down the hall, a still figure in a gray hospital gown stands facing the wall. Cold moonlight through broken windows, peeling paint, wet linoleum with faint reflections. Locked-off wide shot, eye-level, desaturated blue-green palette, deep shadows, film grain. Quiet, uneasy mood. No gore.",
        "elite": "Static locked-off wide shot, 32mm lens, eye-level, of a long derelict hospital corridor at 3am. FOREGROUND: an empty wheelchair angled toward camera, one wheel slowly rotating to a stop, then still. MIDGROUND: peeling sea-green paint, a single overhead fluorescent tube stuttering on and off every few seconds. BACKGROUND, ~20 meters deep and held in sharp focus: a motionless woman in a pale gray hospital gown, facing the wall - a little too tall, arms hanging past her knees, face never shown. The camera never moves. On the second fluorescent flicker she is one step closer, though no step is seen; each blackout is fully black so the reposition hides inside the dark. On the third flicker she is gone from the background and now stands just beside the wheelchair, still facing away. Hold on her for three seconds. Then cut to black. LIGHTING: one failing overhead fluorescent, cold 5600K stutter, plus warm sodium spill from a distant exit sign; deep unlit shadows, no fill, threat lives half in darkness. PALETTE: desaturated sickly green and bruise-blue with a single dull red exit glow. Wet floor reflections, slow settling dust drifting through the light. Heavy 16mm grain, faint gate weave, deep focus. MOOD: dread, stillness, wrongness. No score, no gore, no sudden loud sting - the horror is the proximity and the hold.",
        "negative": "gore, blood splatter, viscera, glowing red eyes, screaming face lunging at camera, cheap jump scare, smiling ghost, full-body CGI monster shown in bright light, cartoon demon, contorted extra limbs, melted artifact faces, oversaturated colors, purple and neon-green fog, fog-machine haze everywhere, flat even lighting, bright cheerful daylight, clean modern renovated interior, lens flares, motion blur mush, watermark, on-screen \"scary\" text, multiple competing subjects, cluttered busy frame, orchestral sting"
    },
    {
        "genre": "documentary",
        "medium": "video",
        "user_idea": "a doc shot of an old fisherman getting his boat ready in the early morning",
        "bad": "A cinematic documentary of an old fisherman, beautiful, epic, 4k, ultra detailed, dramatic lighting, masterpiece, award winning, trending.",
        "improved": "Documentary-style shot of an elderly fisherman preparing his small wooden boat at a harbor in the early morning. Handheld camera, natural overcast light, medium shot, realistic skin and fabric, subtle film grain, muted colors. He is focused on his work and does not look at the camera.",
        "elite": "Observational documentary, cinema verite. ONE subject: a weathered fisherman in his late sixties, gray stubble, an orange oilskin bib over a faded blue wool sweater, kneeling on the deck of a small wooden trawler to coil a wet mooring rope by hand. Location: a working harbor at first light, low tide, the hull streaked with salt and rust, gulls perched on barnacled pilings behind him. Shot size: medium shot, waist-up, subject framed slightly off-center and unaware of the camera - he never looks to lens. Lens: 50mm at shallow depth of field, background boats softening into bokeh. Camera: shoulder-mounted handheld with subtle organic micro-movement, holding first on his hands as they work the rope, then a slow patient reframe up to his face. Lighting: available light only - cold overcast dawn, a soft directional key from the open sky camera-left, a faint catchlight in his eyes, no fill, honest shadow under the brim of his cap. Color: naturalistic and slightly desaturated, true skin tones, a cool blue-gray morning cast; NO teal-orange grade. Texture: fine 16mm-style grain, real wet wood and coarse wool detail, his breath faintly visible in the cold. Motion inside the frame: the rope coiling in his hands, water lapping the hull, one gull lifting off in the background. Single continuous take, roughly 8 seconds, no cuts. Audio: wild ambient only - lapping water, distant gull calls, the creak of rope and timber; sparse measured narration in a low, matter-of-fact register over the top, no music.",
        "negative": "teal-orange cinematic grade, glossy commercial polish, over-stabilized gimbal glide, slow-motion, staged eye contact with camera (in observational shots), actor-perfect studio three-point lighting, softbox glamour, beauty-dish key, swelling orchestral score, sad manipulative piano, lens flare whip-pans, drone hero opener, fake film-burn and light-leak overlays, oversaturated colors, HDR halos, plastic AI skin, waxy over-smoothing, warped hands, extra fingers, duplicated subject, mismatched period props, floating text, watermark, logo, subtitle bar"
    },
    {
        "genre": "nature_wildlife",
        "medium": "image",
        "user_idea": "a fox in the snow",
        "bad": "a beautiful majestic fox in the snow, highly detailed, 4k, 8k, stunning, award winning nature photography, cinematic, hyperrealistic",
        "improved": "A red fox standing in fresh snow during golden hour, telephoto lens, shallow depth of field, sharp focus on the eyes, soft warm backlight, natural winter forest background, wildlife photography, muted natural colors",
        "elite": "Wildlife photograph of a single wild red fox (Vulpes vulpes) in full winter coat, caught mid-pounce in a \"mousing\" dive: front legs tucked to the chest, muzzle angled straight down toward the snowpack, hind legs extended, body arched in a near-vertical leap about half a meter above an open snowfield, hunting a vole beneath the crust. Dense russet-orange pelage, white throat and belly, black-stockinged legs, bushy white-tipped tail streaming behind. Loose powder bursts upward from the launch point with individual snow crystals frozen in mid-air; faint breath vapor at the nostrils. Setting: open boreal meadow at the edge of a bare birch stand, early morning after fresh snowfall. Low winter sun rakes in from camera-left as warm backlight, rim-lighting the fur into a glowing halo and throwing one long cool-blue shadow across the snow. Bright catchlight in the dark amber eye; tack-sharp focus on the eye and muzzle. Shot on a 600mm f/4 super-telephoto from a low, near-ground eye-level position, aperture f/5.6, shutter 1/3200 to freeze the powder, shallow depth of field compressing the out-of-focus birch trunks into soft vertical bokeh. Cool blue shadow tones against warm gold highlights, restrained natural winter palette, fine fur-and-snow-crystal micro-texture, no oversaturation. Documentary wildlife realism.",
        "negative": "cartoon, anthropomorphic, human facial expression, smiling animal, extra limbs, missing limbs, wrong number of legs, fused paws, malformed anatomy, chimera, hybrid animal, two heads, duplicated animal, oversaturated, HDR clown colors, neon glowing eyes, plastic CGI fur, over-smoothed, waxy, blurry eye, soft focus on eye, dead eyes without catchlight, taxidermy stiffness, cluttered distracting background, wrong species markings, wrong biome, zoo fence, cage bars, leash, collar, human hands, watermark, logo, text, signature, award badge, frame border, motion smear on a static subject"
    },
    {
        "genre": "space_cosmos",
        "medium": "video",
        "user_idea": "an astronaut looking at a planet, make it look epic",
        "bad": "epic space scene, beautiful galaxy, stars, planets, nebula, astronaut, 4k, stunning, cinematic, colorful cosmos, breathtaking, ultra detailed, wow amazing masterpiece",
        "improved": "A lone astronaut in a white spacesuit floating in orbit, looking down at a blue Earth-like planet below. Hard sunlight coming from the left, dark starry sky behind. Wide shot, realistic detail on the suit and visor reflection, cinematic photoreal look, high dynamic range.",
        "elite": "Slow constant-velocity orbital tracking shot, 8 seconds, no cuts. SUBJECT: a single lone astronaut in a white EVA suit, tethered to the battered hull of an orbital station, positioned in the lower-left third of the frame, back-lit by a hard white-blue sun just outside frame right. LOWER RIGHT TWO-THIRDS: the curved limb of an ocean planet - deep sapphire sea, swirling white cloud bands, a razor-sharp day/night terminator line cutting diagonally across it, faint golden city lights sparkling on the night side, a thin Rayleigh-blue atmospheric glow along the limb. UPPER BACKGROUND: flat true-black vacuum scattered with pin-sharp, non-twinkling stars and the faint dust-lane band of the Milky Way arcing toward the top-right corner. LIGHTING: single hard key from the off-frame sun, zero fill, jet-black shadow on the astronaut's far side and the station's underside, a bright specular hotspot skating across the gold visor. MOTION: camera drifts slowly and smoothly to the right at constant velocity; the near astronaut and station parallax-shift against the fixed, motionless star field; planet rotates almost imperceptibly. Stars stay perfectly steady and un-blurred. Physically accurate vacuum - silent, no lens-dust streaks, no motion blur on stars, no atmospheric haze in the black. Virtual 50mm lens, shallow orbital drift, no handheld shake, tilted horizon (no true up). Photoreal HDR grade, restrained saturation, subtle film grain, clean highlight roll-off. One dominant subject, deep depth cue by scale.",
        "negative": "twinkling stars, star streaks, motion blur on stars, diffraction spikes on every star, oversaturated rainbow nebula, purple-and-teal gradient sky, dense Hollywood asteroid field, multiple planets or moons crowded impossibly close, atmospheric haze or fog in vacuum, soft even ambient fill light, gray or navy space instead of black, lens-flare spam, fisheye distortion, warped or wobbling horizon, audible sound cues, level tabletop horizon, cartoonish, plastic CGI look, extra limbs on astronaut, malformed helmet, floating text, watermark, logo, UI overlay, low dynamic range, blown-out flat exposure"
    },
    {
        "genre": "religion_mythology",
        "medium": "image",
        "user_idea": "a picture of the greek sea god rising out of a stormy ocean holding his trident",
        "bad": "poseidon god of the sea, epic, powerful, highly detailed, 8k, cinematic lighting, dramatic, masterpiece, trending on artstation, beautiful, ultra realistic, glowing energy",
        "improved": "Poseidon, ancient Greek sea god, rising from a stormy ocean and holding a trident, huge dark waves around him, storm light breaking through heavy clouds, low camera angle looking up at him, moody teal and grey color palette, oil painting style, cinematic and dramatic.",
        "elite": "Low-angle wide shot of a single colossal elder sea-god rising waist-deep out of a black storm-ocean, his body filling the right two-thirds of the frame, turned three-quarters toward camera. Weathered bronze skin crusted with barnacles and kelp, a beard of streaming seawater, both hands gripping a corroded verdigris three-pronged trident held vertically so its tines catch the light. Foreground lower-left: a small wooden sailing ship tilting on a wave crest, tiny against him, giving scale. Background: a towering wall of green-black waves under a low, bruised storm horizon. SINGLE light source - one break in the thunderheads casting a cold silver god-ray straight down onto his face and the trident tines; deep teal shadow fills the wave troughs; foam edges are rim-lit white. Limited palette: slate grey, verdigris bronze, bone-white foam, with one warm amber glint in the eyes. Driving rain and sea-spray streak diagonally across the frame; volumetric mist hangs at the waterline. Mood: ancient, monumental, indifferent. Rendered as painterly oil on canvas in the tradition of J.M.W. Turner's storm-sea light - visible brush texture, atmospheric depth, matte finish, deep focus, horizon kept low. No text, no watermark, no modern objects.",
        "negative": "modern clothing, wristwatch, smartphone, eyeglasses, cars, logos, text, captions, watermark, signature, anime, chibi, cartoon, plastic shiny skin, waxy CGI sheen, extra fingers, fused hands, malformed hands, duplicated trident, two light sources, contradictory shadow directions, flat frontal flash, blown-out HDR, oversaturated rainbow colors, cluttered composition, floating embers everywhere, lens-flare overload, mashed-up sacred symbols from different religions, disrespectful caricature"
    },
    {
        "genre": "biology_science_viz",
        "medium": "video",
        "user_idea": "make a picture of an animal cell showing the organelles inside",
        "bad": "a cell, science, super detailed, 4k, beautiful, glowing blue, futuristic biology, high quality, digital art, microscopic world, amazing",
        "improved": "Cross-section of a eukaryotic animal cell, clean medical-illustration style, clearly showing the nucleus with nucleolus, several mitochondria, rough endoplasmic reticulum, and the Golgi apparatus, accurate organelle shapes, soft neutral gradient background, even lighting, high detail, no text.",
        "elite": "Slow, continuous macro dolly-in through the translucent interior of a single eukaryotic animal cell, rendered as a photorealistic scientific 3D animation in the style of high-end medical visualization. SUBJECT HIERARCHY: the camera drifts past one large ovoid nucleus in the foreground-left, wrapped in a double nuclear envelope pierced by visible nuclear pores, its dense nucleolus glowing faintly within; mid-ground holds three bean-shaped mitochondria with clearly folded inner cristae; the deep background is a soft, out-of-focus haze of ribosome-studded rough endoplasmic reticulum. MOTION: only the camera moves, a slow steady forward creep; organelles drift gently as if suspended in viscous cytosol - no morphing, no shape changes, membranes hold their form. LIGHTING: soft volumetric key from the upper right, strong subsurface scattering through the gel-like translucent cytoplasm, a thin rim light separating each glossy wet membrane, restrained teal-and-amber color grade. LENS: 100mm macro look, shallow depth of field; focus holds on the nuclear pores, then a gentle rack focus hands off to the mitochondria as they pass. SCALE: cellular, everything soft-edged and wet. Dark neutral background, no text, no labels. 5 seconds, 24fps, smooth and uninterrupted.",
        "negative": "text, labels, letters, numbers, gibberish writing, watermark, signature, left-handed DNA helix, sci-fi HUD, targeting reticle, circuit board pattern, binary code, glowing blue neon network, floating hexagons, lens flare, bokeh orbs, cartoon outlines, thick black outlines, featureless bubble cells, nucleated red blood cells, flat disc blood cells, extra or duplicated organelles, morphing shapes, warping membranes, unnatural perfect symmetry, oversaturated rainbow colors, dust particles, plastic surfaces, low detail, blurry mush"
    },
    {
        "genre": "math_abstract_viz",
        "medium": "image",
        "user_idea": "i want a smart-looking techy math art thing, like a glowing shape made of lines, for a desktop wallpaper",
        "bad": "fractal, sacred geometry, mathematics, abstract background, colorful, glowing, symmetrical, 4k, ultra detailed, intricate, trending on artstation, digital art, beautiful, masterpiece",
        "improved": "A glowing generative structure on a dark background, fine intricate lines forming a symmetrical mathematical pattern, blue and purple color scheme, centered composition, soft glow, high detail, minimal and clean, abstract algorithmic art, orthographic view, no text.",
        "elite": "A single strange-attractor filament structure centered in a deep black void - the traced path of a chaotic system rendered as roughly forty thousand hair-fine luminous threads that swirl into two nested focal lobes and never intersect. Density is the entire image: the two lobe centers are the brightest and most tightly woven, threads fanning outward into sparse, fading wisps toward the frame edges. Orthographic projection, no perspective distortion; the subject occupies the central ~70% of a square frame with clean, deliberate negative space around it. Color is bound to local thread density on ONE perceptual gradient - near-black indigo in the sparse outer field, rising through deep violet and teal to near-white cyan at the hottest cores - with a single restrained magenta rim on the highest-density crest only. Emissive material: the threads are their own light source, faint additive bloom where they bundle, no external key light, no cast shadow. Micro-detail: individual sub-pixel strands with anti-aliased falloff, a fine-grained pen-plotter texture at 100% zoom. Flat matte void background - no grid, no gradient sky, no floor. Mood: precise, cold, quiet, hypnotic. High-resolution generative plot, 1:1, crisp edges. No text, no numbers, no axes, no watermark.",
        "negative": "text, numbers, equations, labels, axis ticks, gridlines behind subject, watermark, signature; muddy rainbow gradient, HSV-wheel spin, oversaturated neon-on-black soup; blurry, soft, low-detail, jpeg artifacts; lens flare, bokeh, photographic depth-of-field on a flat pattern; cluttered or busy background; two competing focal subjects; broken or warped symmetry where symmetry is intended; melted globby forms, plasticky glossy 3D render, chrome specular; crossing threads in a non-crossing attractor; skewed perspective on an orthographic plot; the glowing \"AI brain\" network sphere; motivational-poster gloss"
    },
    {
        "genre": "fine_art",
        "medium": "image",
        "user_idea": "a painting of a woman standing by a window with nice light",
        "bad": "beautiful masterpiece painting of a gorgeous woman by a window, highly detailed, intricate, stunning, 4k, 8k, octane render, unreal engine, trending on artstation, award winning, cinematic, hyperrealistic, volumetric lighting",
        "improved": "Oil painting of a young woman standing beside a window in soft daylight, Dutch Golden Age style, warm dim interior, detailed fabric folds, chiaroscuro lighting, muted earthy palette, portrait orientation, visible brushwork.",
        "elite": "Oil-on-linen half-length portrait of a single solitary young woman standing at a leaded-glass casement window, turned three-quarters toward cool north light, gaze lowered. One light source only: soft daylight rakes from the left across her cheekbone and the folds of a slate-blue wool shawl, then falls to deep warm-umber shadow on the shaded side - restrained chiaroscuro in the manner of Dutch Golden Age interior painting. Technique: thin transparent glazes over a warm ochre imprimatura in the shadows, low impasto catching the light on linen highlights, the window lead, and the knuckles; soft sfumato transitions at the jaw and hairline; confident directional brushwork visible up close. Limited earth palette - lead white, yellow ochre, raw umber, a single restrained vermilion accent at the lips. Background: a dim plastered interior receding into shadow, a dull pewter jug on a bare oak table set as repoussoir in the lower-right corner. Composition on a rising diagonal, the figure on the left third, quiet negative space of the wall balancing the right. Surface reads as a real object: fine canvas weave, faint craquelure, the warm cast of aged varnish. Even, glare-free museum documentation lighting; bare artwork filling the frame, no wall or frame shown. Portrait orientation, 4:5.",
        "negative": "3D render, octane, unreal engine, CGI, photorealistic photograph, HDR, airbrushed plastic skin, digital-smooth gradients, glossy sheen, oversaturated neon, modern clothing, wristwatch, smartphone, cartoon, anime, vector, clip-art, trending-on-artstation logo, watermark, printed signature text, gallery wall and ornate gold frame (when bare artwork is wanted), contradictory multiple light sources, lens flare, bokeh, motion blur, extra fingers, warped hands, asymmetrical melted eyes, muddy grey mush, over-centered dead-symmetrical layout"
    },
    {
        "genre": "drama",
        "medium": "video",
        "user_idea": "a woman getting bad news on the phone",
        "bad": "a beautiful woman crying on the phone because she got very sad news, tears streaming down her face, extremely emotional and heartbreaking, cinematic dramatic lighting, 4k ultra hd, masterpiece, trending on artstation, highly detailed, award winning photography",
        "improved": "Medium close-up of a woman in her late thirties standing at a kitchen counter, a phone held to her ear as she listens. Still expression, unfocused eyes, lips slightly parted - she is absorbing the news, not crying. Soft daylight from a window camera-left, muted natural color, true skin tones. 50mm, shallow depth of field, eye-level. Lived-in kitchen softened behind her. Quiet, restrained, realistic.",
        "elite": "Single continuous 8-second take. Locked-off frame that pushes in slowly, roughly ten percent over the shot. Medium close-up, eye-level, 85mm-equivalent, shallow depth of field so the kitchen behind her dissolves into muted shapes. Subject: one woman, around forty, tired unretouched skin with visible pores and faint under-eye shadows, dark hair loosely tied, a worn grey cardigan. She stands at a kitchen counter in early morning, a phone held loosely to her ear, her free hand flat on the counter taking her weight. She is listening, not speaking. Across the shot her face barely moves - a slow blink, the jaw tightening, her gaze drifting down and off-frame to the left as the words land. She does not cry. Her breathing shortens once, a single caught breath. Lighting: one motivated source, cool overcast daylight through a window camera-left, soft and directional, wrapping the near side of her face and leaving the far side in gentle shadow; a dim practical lamp glows warm in the deep background. Color: desaturated, neutral true skin tones, no orange-and-teal grade, muted greens and greys in the room. Composition: she sits slightly off-center with negative space to her right; an out-of-focus mug and a scatter of unopened mail rest on the counter. Sound: room tone, refrigerator hum, a wall clock, faint traffic through glass; no music; the only swell is that one caught breath. Naturalistic documentary realism, restrained and quiet. No melodrama, no falling tears, no camera shake, no cuts, no text or captions.",
        "negative": "melodrama, theatrical overacting, exaggerated grief, single glycerin tear, tears streaming, crying in the rain, wailing, hands sliding down a wall, sunset silhouette embrace, glamour retouching, flawless plastic skin, heavy makeup on a grieving face, orange-and-teal grade, oversaturated, HDR halos, symmetrical studio beauty lighting, ring-light catchlights, dutch tilt, lens flare spam, blank stare into camera, on-the-nose expression, extra fingers, deformed hands, mismatched eyes, warped face, text, watermark, subtitles, fast cuts, whip pans, showy camera moves, motion-blur smear"
    },
    {
        "genre": "product_ad",
        "medium": "image",
        "user_idea": "make an ad for my new perfume",
        "bad": "a beautiful perfume bottle, luxury, high quality, 4k, professional, amazing lighting, best quality, trending on instagram, cinematic, stunning, elegant ad, ultra detailed",
        "improved": "Luxury perfume bottle product shot. A rectangular faceted glass bottle filled with amber liquid, brushed-gold cap, standing on a black marble surface against a dark gradient background. Studio lighting from the side with a rim light behind the bottle to make the liquid glow, soft reflection on the marble beneath. Shot on a macro lens, sharp focus on the bottle, some empty space at the top for text. Premium, elegant, photorealistic commercial photography.",
        "elite": "Commercial product hero shot, editorial luxury still-life. SUBJECT: one faceted rectangular glass perfume bottle, half-filled with warm amber liquid, brushed-gold cylindrical cap, standing dead-center in the lower-middle third of the frame. SCENE: the bottle rests on a honed black marble slab with fine grey veining; behind it, a seamless graphite-to-charcoal gradient sweep backdrop. LIGHTING: dark-field studio setup - a large softbox key from camera-left at 45 degrees sculpts a soft tonal gradient down the glass; a narrow strip rim light from behind-right defines the bottle's right edge and back-lights the amber liquid so it glows with sub-surface scattering; black flags on both sides keep the glass deep and glossy so the form reads through controlled specular highlights rather than flat fill; one crisp vertical catchlight runs down the front bevel. A faint cool mist drifts low across the marble. CAMERA: 100mm macro lens, f/9 for edge-to-edge sharpness, eye-level three-quarter angle; bottle tack-sharp, backdrop falling to a soft gradient. COMPOSITION: wide negative space in the upper third reserved for copy. PALETTE: warm amber and brushed gold against cool graphite and black, restrained and premium. Photoreal high-end commercial product photography, clean symmetric composition, undistorted glass, no text, no logo, no props.",
        "negative": "warped or asymmetric bottle, tilted or oval bottle opening, garbled text, misspelled brand name, distorted logo, extra caps or lids, duplicated product, floating product with no grounded shadow, shadow direction inconsistent with key light, plastic CGI sheen, waxy over-smooth surface, blown-out clipped highlights, muddy or warped reflections, fingerprints, dust specks, smudges, cluttered background, distracting props, oversaturated colors, HDR halos, chromatic aberration, lens flare, low-resolution, jpeg artifacts, wrong perspective, fisheye distortion, watermark"
    },
    {
        "genre": "war_strategy",
        "medium": "video",
        "user_idea": "make an epic medieval battle scene, huge army, looks cinematic",
        "bad": "epic medieval war, thousands of soldiers fighting, blood everywhere, dramatic, cinematic, 4k, ultra realistic, hyper detailed, masterpiece, best quality, trending on artstation",
        "improved": "Wide cinematic shot of a medieval battlefield at dawn, two armies of infantry with spears and banners massed on a muddy field under an overcast grey sky, low fog, desaturated color palette, shot on a long lens with shallow depth of field, tense and grave mood, subtle film grain",
        "elite": "Cinematic wide shot, slow 8-second dolly push-in on a single weathered field commander standing at the crest of a frost-covered ridge at first light. She wears a mud-caked wool greatcoat, no helmet, breath fogging in the freezing air. Below and beyond her, a valley floor packed with roughly ten thousand massed pikemen stands motionless in low ground fog, their tall spears forming a dense vertical forest that recedes into atmospheric haze. Rows of dark banners hang limp, heavy with dew. Scene hierarchy - foreground: her gloved hand resting on a sheathed sword; midground: two signal officers waiting one step behind; background: the fog-drowned army and a pale grey dawn sky bleeding faint sodium-orange at the horizon. Camera: 85mm telephoto lens compressing the ranks so the army feels bottomless, medium-shallow depth of field, commander sharp, distant ranks softened by haze. Motion: near-still - only slowly drifting fog, banners stirring once, and the commander's fogged breath; the push-in is glacial, steady, gimbal-smooth. Lighting: cold overcast dawn, soft directional key from camera-left, desaturated steel-blue and ash palette with one warm sodium-orange accent at the horizon. Mood: grave, tense, the held breath before violence. Subtle 35mm film grain. No text, no on-screen graphics, no HUD.",
        "negative": "gratuitous gore, dismemberment, blood splatter as spectacle, anachronistic modern gear on period soldiers, duplicated or fused limbs, extra fingers, warped faces, bent or melting weapons, floating figures, disconnected shadows, fake unreadable banner text, faux-Latin gibberish, video-game HUD, health bars, on-screen graphics, motion-blur smear, oversaturated colors, orange-teal grade overkill, cluttered composition with no clear subject, lens-flare spam, cartoon proportions, plastic CGI sheen, low-detail mush in background ranks, cheerful even lighting, comic exaggeration, clean unweathered armor"
    },
    {
        "genre": "mystery_noir",
        "medium": "video",
        "user_idea": "a detective in the rain looking for a killer in the city at night",
        "bad": "a noir detective in the rain at night, cinematic, moody atmosphere, mysterious vibes, dramatic lighting, dark and gritty, highly detailed, 8k, ultra realistic, masterpiece, trending on artstation",
        "improved": "A lone detective in a dark rain-soaked overcoat and hat stands under a single streetlight on a wet cobblestone street at night, heavy rain falling. Hard amber light from the lamp overhead casts one long shadow across the stones; the rest of the street fades into darkness. Low-key lighting, high contrast, desaturated color, 40mm lens, eye-level, quiet and watchful.",
        "elite": "Medium-wide shot, slow 12-second dolly-in on a single subject: a weary male detective, mid-40s, unshaven, standing alone under a failing sodium-vapor streetlamp on a rain-slick cobblestone street at 2 a.m. He wears a dark, rain-soaked wool overcoat with the collar turned up; water beads and runs off the brim of his hat. A lit cigarette is cupped low in one hand, a thin curl of smoke rising and bending in the wet air. He is not moving - he is waiting for someone who is late.\n\nCamera: 40mm lens, starting eye-level and settling to a slight low angle as the dolly creeps in. Subject held left-of-center; the empty wet street recedes into deep black behind him. Deep focus so the far end of the street and the near cobbles both stay sharp. Aspect ratio 2.39:1, 24fps.\n\nLighting: single hard key from the overhead sodium lamp - warm amber, raking straight down, carving a long hard shadow across the cobbles. Everything beyond the pool of light crushes to near-black (low-key, chiaroscuro, high contrast). One faint cool rim from a distant shop window catches the edge of his right shoulder. No fill on the shadow side of his face - let half of it fall to black.\n\nMotion: heavy rain falls in visible streaks through the cone of the lamp; puddles ripple and throw broken amber reflections; his breath fogs faintly. Midway through the push-in, an unseen car passes off-frame to the left - its headlights sweep one hard moving shadow across the wet brick wall behind him, then vanish, returning the street to darkness.\n\nPalette: heavily desaturated - sodium-amber highlights against blue-black shadow, wet-asphalt sheen everywhere, no bright or saturated colors.\n\nFilmic grain, subtle anamorphic character in the highlights. No text, no captions, no watermark, no on-screen titles.",
        "negative": "flat even lighting, bright daylight, overhead soft fill, clean dry streets, cheerful saturated colors, HDR glow, blown-out highlights, teal-orange over-grade, glossy plastic skin, smiling subject, cluttered busy background, modern glass skyscrapers, neon cyberpunk palette, lens flare spam, cartoon rain / white streak noise, fog-machine haze with no source, extra fingers, warped hands, distorted face, duplicated limbs, text, watermark, logo, captions, low contrast, muddy grey shadows, everything evenly lit"
    },
    {
        "genre": "comedy",
        "medium": "image",
        "user_idea": "make a funny pic of my cat like it's a serious business boss",
        "bad": "funny cat boss meme, hilarious, lol, business cat",
        "improved": "A cat sitting in an office chair behind a desk wearing a small tie, looking serious like a boss, office in the background, bright lighting, funny.",
        "elite": "A single locked-off medium-wide shot, camera at desk height, dead-center symmetrical framing. A fluffy orange tabby sits bolt upright in an oversized black leather executive chair behind a heavy mahogany boardroom desk, both front paws planted flat on the desk like a chairman about to deliver bad news. It wears a slightly-too-large charcoal pinstripe suit jacket, collar askew, and a crooked red silk tie knotted a touch too tight. Its expression is flat and unimpressed - half-lidded eyes staring dead into the lens with total deadpan authority. On the desk: one untouched espresso in a comically tiny cup, a blank brass nameplate, and a toppled stack of paperwork frozen mid-slide, one inch above the floor, about to spill. Behind the cat, a floor-to-ceiling window shows a grey corporate skyline; a single wilting potted plant leans in the corner, indifferent to the chaos. Bright, flat, even high-key office lighting, soft shadows, cool fluorescent-white balance, everything crisply in focus. Photographic realism, 50mm-lens look, moderate depth of field keeping the cat and desk sharp. The humor is bone-dry: a small animal treated with the full gravity of a CEO, captured one beat before the papers hit the floor. No text, no captions, no clutter competing with the cat.",
        "negative": "garbled text, warped or nonsense lettering, meme caption bar, watermark, melted or distorted animal face, extra limbs, extra fingers, malformed paws, clown makeup, googly cartoon eyes, grotesque rubber-face distortion, full-frame motion blur hiding the peak moment, dark muddy underexposed lighting, cluttered busy background, multiple competing subjects, second unrelated gag, laughing crowd, canned-laughter reactions, oversaturated noise, chaotic messy composition"
    },
    {
        "genre": "adult_sensual",
        "medium": "image",
        "user_idea": "a couple in bed, romantic, sexy vibe",
        "bad": "a beautiful sexy couple in bed, romantic, passionate, hot, sensual, 4k, ultra realistic, masterpiece, best quality, highly detailed, beautiful lighting, trending on artstation",
        "improved": "Intimate photo of a couple in a dim bedroom at night. Warm lamplight from one side, the woman resting her head against the man's chest, both relaxed. Soft focus, shallow depth of field, 85mm lens look, cozy romantic mood, muted warm color grade, subtle film grain.",
        "elite": "Photographic still, one intimate two-shot. A man and a woman, both clearly adults, stand chest to chest in a shadowed bedroom with a hand's breadth of space still held between their lips - the almost-kiss, not the kiss. She tilts her chin up, eyes half-lowered; his open hand rests at the small of her back, fingers spread against bare skin where her oversized shirt has slipped off one shoulder. Frame it as a tight medium close-up from a low three-quarter angle, their faces on the upper-third eyeline, breathing room of negative space to camera-left, shot slightly through the soft out-of-focus edge of a sheer curtain in the extreme foreground so the couple reads sharp behind a gauzy veil. Single motivated key: a warm bedside lamp about 2800K, low and camera-left, giving short Rembrandt light that sculpts her cheekbone and throat and lets the far side of both faces fall into deep shadow. A cool moonlight-blue rim from the window camera-right traces the edge of his shoulder and her hairline, separating skin from the dark; negative fill on the shadow side deepens the contour. Color grade: honey-amber highlights against desaturated plum shadows, true luminous skin with visible pore texture and subsurface warmth, a faint sheen along the collarbone. Shot on an 85mm lens at f/1.4, focus locked on the point of near-contact between their mouths, background dissolving into creamy bokeh with soft round lamp-glow orbs. Fine 35mm film grain, gentle halation on the highlights. Mood: charged, unhurried, tender and tense. Tags: intimate portrait photography, low-key chiaroscuro, motivated warm practical key, cool window rim light, negative fill, shallow depth of field, 85mm f1.4, film grain, halation, skin-and-light, cinematic, high detail.",
        "negative": "child, minor, teen, underage, childlike features, youthful face (all subjects must read as adults), extra fingers, fused or merged limbs, deformed hands, mutated fingers, warped anatomy, extra limbs, duplicate faces, disfigured, plastic airbrushed skin, waxy poreless over-smoothed skin, oily silicone gloss, flat on-camera flash, harsh direct flash, blown-out highlights, muddy crushed shadows, contradictory light sources, HDR halos, oversaturated, cluttered busy background, rose petals on the bed, cheesy heart props, single red rose, stock-photo laughing couple, text, watermark, logo, signature, lowres, jpeg artifacts, blurry, out-of-focus subject"
    }
]
