"""Video-story mode for demo.plan: a continuous product-presentation SCRIPT, not a slideshow.

The default demo plan is a shot list with burned-in subtitles + an image set. That reads like slides.
A *video* presentation is one flowing story: each beat defines the BACKGROUND/scene the video shows and
the DIALOGUE the host says over it, generated by a text-to-video model (Veo-3.1 class, native voice +
lip-sync). This module turns a repo/docs brief into a story-writing PACK -- the arc, the real features,
the locked recurring presenter, and the exact scene+dialogue output format -- which the agent's model
fills into the finished script. The deterministic pack + the plain-text renderer are what live here;
the prose is the model's job (that is what makes it a story instead of a template).
"""
from __future__ import annotations

from dataclasses import dataclass, field


def _presenter_descriptor(presenter: str) -> str:
    """Expand a short preset key (woman/man/girl/boy/person) or use a rich free-form descriptor as-is."""
    from core.demo_planner import _PRESENTERS

    text = str(presenter or "").strip()
    key = text.lower()
    if key in _PRESENTERS:
        return _PRESENTERS[key]
    return text or _PRESENTERS["person"]


def _story_beats(feature_count: int) -> list[str]:
    """The narrative arc: hook + problem, the reveal, a few feature beats, the proof peak, a CTA.

    Feature beats are capped at 4 so the film stays ~7-9 shots and breathes; more features are woven
    across those beats rather than getting a shot each (which reads as a list, not a story).
    """
    beats = ["hook", "problem", "reveal"]
    beats += ["feature"] * min(4, max(1, feature_count))
    beats += ["proof", "cta"]
    return beats


@dataclass(frozen=True)
class VideoStoryShot:
    n: int
    seconds: float
    beat: str
    scene: str        # the BACKGROUND/video: a self-contained render-ready shot description
    dialogue: str     # what the host SAYS on camera in this shot ("" for a pure-visual beat)
    sound: str = ""

    def to_dict(self) -> dict:
        return {"n": self.n, "seconds": self.seconds, "beat": self.beat,
                "scene": self.scene, "dialogue": self.dialogue, "sound": self.sound}

    @classmethod
    def from_dict(cls, d: dict, *, index: int) -> VideoStoryShot:
        d = d or {}
        try:
            secs = float(d.get("seconds") or 0)
        except (TypeError, ValueError):
            secs = 0.0
        return cls(
            n=int(d.get("n") or index),
            seconds=max(0.0, secs),
            beat=str(d.get("beat") or "").strip(),
            scene=str(d.get("scene") or "").strip(),
            dialogue=str(d.get("dialogue") or "").strip(),
            sound=str(d.get("sound") or "").strip(),
        )


@dataclass(frozen=True)
class VideoStoryScript:
    product: str
    tagline: str
    presenter: str
    total_seconds: int
    logline: str = ""
    shots: tuple[VideoStoryShot, ...] = ()

    def to_dict(self) -> dict:
        return {"product": self.product, "tagline": self.tagline, "presenter": self.presenter,
                "total_seconds": self.total_seconds, "logline": self.logline,
                "shots": [s.to_dict() for s in self.shots]}

    def to_plaintext(self) -> str:
        lines = [
            f"{self.product} - PRODUCT PRESENTATION VIDEO (one continuous story)",
            f"Runtime: {self.total_seconds}s  |  {len(self.shots)} shots  |  "
            "text-to-video (native voice + lip-sync)",
            f"Host: {self.presenter}",
        ]
        if self.logline:
            lines.append(f"Logline: {self.logline}")
        for s in self.shots:
            lines += [
                "",
                "-" * 64,
                f"SHOT {s.n}   [{_fmt_secs(s.seconds)}]   {s.beat.upper()}",
                "",
                "SCENE (video / background):",
                f"  {s.scene}",
                "",
            ]
            if s.dialogue:
                lines += ["SHE SAYS (on camera):", f'  "{s.dialogue}"']
            else:
                lines.append("SHE SAYS: (no line - visual beat)")
            if s.sound:
                lines += ["", f"SOUND: {s.sound}"]
        return "\n".join(lines)

    def narration_only(self) -> str:
        return " ".join(s.dialogue for s in self.shots if s.dialogue)


def _fmt_secs(value: float) -> str:
    return f"{int(value)}s" if float(value).is_integer() else f"{value:g}s"


def story_from_model(product: str, tagline: str, presenter: str, total_seconds: int, data) -> VideoStoryScript:
    """Normalize a model's returned story (a dict or a list of shot dicts) into a VideoStoryScript.

    Tolerant: accepts ``{"logline":..., "shots":[...]}`` or a bare ``[...]`` of shots; coerces types and
    drops shots that have neither a scene nor dialogue.
    """
    logline = ""
    raw_shots = data
    if isinstance(data, dict):
        logline = str(data.get("logline") or "").strip()
        raw_shots = data.get("shots") or []
    shots: list[VideoStoryShot] = []
    if isinstance(raw_shots, list):
        for i, item in enumerate(raw_shots, start=1):
            if not isinstance(item, dict):
                continue
            shot = VideoStoryShot.from_dict(item, index=i)
            if shot.scene or shot.dialogue:
                shots.append(shot)
    return VideoStoryScript(
        product=str(product or "").strip(), tagline=str(tagline or "").strip(),
        presenter=_presenter_descriptor(presenter), total_seconds=int(total_seconds or 0),
        logline=logline, shots=tuple(shots),
    )


@dataclass
class VideoStoryPack:
    """The deterministic brief handed to the model, plus the instruction that makes it write the story."""
    product: str
    tagline: str
    presenter: str
    total_seconds: int
    features: list[dict] = field(default_factory=list)
    arc: list[str] = field(default_factory=list)
    instruction: str = ""

    def to_dict(self) -> dict:
        return {"product": self.product, "tagline": self.tagline, "presenter": self.presenter,
                "total_seconds": self.total_seconds, "features": self.features,
                "arc": self.arc, "instruction": self.instruction}


def _presenter_from_set(cset) -> str:
    """A host descriptor built from a saved creative set's locked character(s)."""
    parts = []
    for c in getattr(cset, "characters", ()) or ():
        seg = f"{c.name} - {c.appearance}".strip(" -")
        if getattr(c, "wardrobe", ""):
            seg += f", wearing {c.wardrobe}"
        if seg:
            parts.append(seg)
    return "; ".join(parts)


def _locked_world_block(cset) -> str:
    """The set's world/style/story/voice/negatives, so the model keeps the WHOLE set on-model."""
    lines = []
    world = ". ".join(x for x in (cset.setting.strip(), cset.background.strip()) if x)
    if world:
        lines.append(f"Setting / world (keep identical every shot): {world}")
    style = ", ".join(x for x in (cset.style.strip(),
                                  (f"palette {cset.palette}" if cset.palette.strip() else ""),
                                  cset.mood.strip()) if x)
    if style:
        lines.append(f"Visual style (locked): {style}")
    if cset.story.strip():
        lines.append(f"Story world: {cset.story.strip()}")
    voices = "; ".join(f"{c.name}'s voice: {c.voice}" for c in cset.characters if c.voice)
    if voices:
        lines.append(f"Voice (locked): {voices}")
    if cset.negative.strip():
        lines.append(f"Never show: {cset.negative.strip()}")
    return "\n".join(lines)


def build_video_story_pack(brief, *, presenter: str = "", total_seconds: int = 0,
                           set_name: str = "") -> VideoStoryPack:
    """Turn a demo brief into a video-story writing pack for the agent's model to complete.

    ``brief`` is a ``core.demo_planner.DemoBrief`` (product_name, tagline, features, presenter,
    total_seconds). ``presenter``/``total_seconds`` override the brief when given. When ``set_name``
    names a saved creative set, the host and the whole world/style are locked from that set so a series
    of product videos stays on-model.
    """
    product = str(getattr(brief, "product_name", "") or "the product").strip()
    tagline = str(getattr(brief, "tagline", "") or "").strip()
    total = int(total_seconds or getattr(brief, "total_seconds", 0) or 90)

    cset = None
    if set_name:
        try:
            from core.creative_set import get_set
            cset = get_set(set_name)
        except Exception:
            cset = None
    locked_world = ""
    if cset is not None and cset.characters:
        presenter_text = _presenter_from_set(cset) or _presenter_descriptor(presenter or "person")
        locked_world = _locked_world_block(cset)
    else:
        presenter_text = _presenter_descriptor(presenter or getattr(brief, "presenter", "") or "person")

    features = [
        {"name": str(getattr(f, "name", "")).strip(), "blurb": str(getattr(f, "blurb", "")).strip()}
        for f in (getattr(brief, "features", ()) or ())
        if str(getattr(f, "name", "")).strip()
    ]
    arc = _story_beats(len(features) or 1)

    feature_lines = "\n".join(
        f"  - {f['name']}" + (f": {f['blurb']}" if f["blurb"] else "") for f in features
    ) or "  - (derive the standout capabilities from the product page below)"

    instruction = _render_instruction(product, tagline, presenter_text, total, feature_lines, arc,
                                      locked_world=locked_world, feature_count=len(features))
    return VideoStoryPack(product=product, tagline=tagline, presenter=presenter_text,
                          total_seconds=total, features=features, arc=arc, instruction=instruction)


def build_video_story_revise_prompt(pack: VideoStoryPack, draft: str) -> str:
    """A self-critique + rewrite pass: the model fixes its own draft against the common failure modes.

    A single revise turn is the biggest quality lever for a weaker local model -- it catches the broken
    timing math, empty hook/CTA lines, generic scenes, and feature-listing that a first pass leaves in.
    """
    return (
        f"Below is a draft video script for {pack.product}. Revise it into a stronger final version and "
        "return ONLY the revised script in the SAME format (a 'Logline:' line, then the shots).\n\n"
        "Fix these specifically:\n"
        f"  - Per-shot seconds MUST add up to exactly {pack.total_seconds}s -- recompute if they do not.\n"
        f"  - Keep it to {len(pack.arc)} shots; merge any weak or redundant beats.\n"
        "  - EVERY shot needs a spoken SHE SAYS line, especially the first (hook) and last (CTA) -- fill "
        "any empty ones.\n"
        "  - Rewrite generic scenes into render-ready shots: camera move + lighting + framing + one "
        "concrete on-screen visual each.\n"
        "  - Weave the features through the story instead of listing them one per shot; cut verbatim "
        "blurbs and doc jargon (e.g. do not say 'L3').\n"
        "  - Make the strongest proof the emotional peak with its own beat.\n"
        "  - Punch up flat dialogue so it sounds like a real host.\n"
        f"  - Keep the same host and world: {pack.presenter}.\n\n"
        "DRAFT TO REVISE:\n" + str(draft or "")
    )


_ARC_HELP = {
    "hook": "cold open that names the tension the product resolves - make the viewer feel the problem",
    "problem": "sharpen the pain of the status quo",
    "reveal": "introduce the product as the turn; say its name and its one-line promise",
    "feature": "one feature, shown as story (host demonstrates it, not recites it)",
    "proof": "the single most distinctive thing, landed as the emotional peak, then a quick sweep of the rest",
    "cta": "a clean, human call to action",
}


def _render_instruction(product: str, tagline: str, presenter: str, total: int,
                        feature_lines: str, arc: list[str], *, locked_world: str = "",
                        feature_count: int = 0) -> str:
    arc_str = " -> ".join(arc)
    shot_count = len(arc)
    per = max(6, round(total / max(1, shot_count)))
    locked_block = (
        "\n\nLOCKED SET (from a saved creative set - keep ALL of this identical across every shot so a "
        "series of videos stays on-model):\n" + locked_world if locked_world else ""
    )
    rules = (
        "\n\nNON-NEGOTIABLE RULES (a weak draft ignores these - do not):\n"
        f"  1. EXACTLY {shot_count} shots. Each shot's seconds MUST add up to exactly {total}s "
        f"(about {per}s each - adjust so the sum is {total}). State each shot's seconds in its header.\n"
        "  2. EVERY shot has a spoken SHE SAYS line - the hook (shot 1) and the CTA (last shot) "
        "INCLUDED. Never leave a line empty.\n"
        "  3. Each SCENE is render-ready: name the CAMERA move, the LIGHTING, the FRAMING, and at least "
        "one CONCRETE on-screen visual (a UI panel, a diagram, a receipt card, a toggle). Never a "
        "generic 'she sits and smiles'.\n"
        f"  4. WEAVE the {feature_count or 'listed'} features through the feature and proof beats as "
        "STORY - do NOT give one feature its own shot in list form, and do NOT paste the feature blurbs "
        "verbatim.\n"
        "  5. The PROOF beat is the emotional PEAK: dramatize the single most distinctive real capability "
        "(let it breathe, its own moment).\n"
        "  6. Dialogue is punchy spoken host copy - say it like a person, not a changelog. Strip doc "
        "jargon, version strings, and internal labels (e.g. never say 'L3').\n"
    )
    return (
        f"Write a PRODUCT-PRESENTATION VIDEO SCRIPT for {product}, hosted by ONE recurring on-camera "
        f"presenter: {presenter}. She is the SAME character in every shot (continuity matters).\n\n"
        "This is a VIDEO, not a slideshow. It is generated by a text-to-video model (Veo-3.1 class) that "
        "renders native audio + lip-synced speech. For EACH shot give a SCENE (the render-ready "
        "background/video), a SHE SAYS line (her on-camera words - the model voices + lip-syncs them), "
        "and a SOUND cue. Tell ONE continuous STORY with an arc that builds to a payoff, not a list of "
        "features read aloud."
        + rules
        + f"\nSTORY ARC ({shot_count} shots, in order): {arc_str}\n"
        + "".join(f"  - {b}: {_ARC_HELP[b]}\n" for b in dict.fromkeys(arc) if b in _ARC_HELP)
        + f"\nPRODUCT: {product}"
        + (f"\nONE-LINE: {tagline}" if tagline else "")
        + "\nFEATURES (real - weave these into the story, do not just list them):\n"
        + feature_lines
        + locked_block
        + "\n\nHONESTY: claim only what the product page states. Do not invent audits, enterprise/mainnet "
        "status, or capabilities that are not listed.\n\n"
        "OUTPUT FORMAT (plain text, exactly this shape per shot):\n"
        "SHOT <n>   [<seconds>s]   <BEAT>\n"
        "SCENE (video / background):\n"
        "  <render-ready scene>\n"
        "SHE SAYS (on camera):\n"
        '  "<her spoken line>"\n'
        "SOUND: <cue>\n\n"
        "Begin with one 'Logline:' line, then the shots in order. No image set - this is a video."
    )
