"""Fallback web search using HTML scraping of public search engines.

Named google_html for provider-order compatibility. Tries Yahoo Search first,
then Brave Search as fallback.

Yahoo leads because Brave rate-limits this box hard: measured over eight varied
queries Brave returned 429 on five of them (~2.6s each before the fallback even
starts), while Yahoo answered all eight in ~1.1s. Brave still runs second because
its snippets are cleaner when it does answer, and it covers Yahoo's intermittent
500 ("INKApi Error").
"""

from __future__ import annotations

import re
import time
import urllib.error
import urllib.parse
import urllib.request
from html import unescape

from core.remote_fetch_policy import RemoteFetchRefusedError, open_remote

_USER_AGENT = (
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) "
    "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

_TAG_RE = re.compile(r"<[^>]+>")


def _clean(raw: str) -> str:
    return unescape(_TAG_RE.sub("", raw)).strip()


def google_html_search(
    query: str, *, max_results: int = 8, timeout_s: float = 10.0,
) -> list[dict[str, str]]:
    """Search using available HTML search engines.

    Tries Yahoo Search, then falls back to Brave Search.
    """
    text = (query or "").strip()
    if not text:
        return []

    for search_fn in (_yahoo_search, _brave_search):
        try:
            results = search_fn(text, max_results=max_results, timeout_s=timeout_s)
            if results:
                return results
        except RemoteFetchRefusedError:
            # The turn is not permitted to reach the network; that is a policy
            # verdict, not "the web had nothing", so it must surface rather than
            # read as an empty result.
            raise
        except Exception:
            continue

    return []


def _brave_search(query: str, *, max_results: int, timeout_s: float) -> list[dict[str, str]]:
    params = urllib.parse.urlencode({"q": query})
    html = _fetch(
        f"https://search.brave.com/search?{params}", timeout_s=timeout_s,
    )
    blocks = html.split('class="snippet  svelte')[1:]
    results: list[dict[str, str]] = []
    seen: set[str] = set()

    for block in blocks:
        chunk = block[:4000]
        href_m = re.search(r'href="(https?://[^"]+)"', chunk)
        if not href_m:
            continue
        url = href_m.group(1).strip()
        domain = _domain(url)
        if not domain or url in seen or domain in _BRAVE_SKIP:
            continue
        seen.add(url)

        title_m = re.search(r'snippet-title[^>]*>(.*?)</(?:span|a)', chunk, re.DOTALL)
        title = _clean(title_m.group(1)) if title_m else ""
        if not title:
            continue

        long = [t.strip() for t in re.findall(r">([^<]{40,})<", chunk) if t.strip() != title]
        snippet = _clean(long[0])[:300] if long else ""
        results.append({"title": title, "url": url, "snippet": snippet})
        if len(results) >= max_results:
            break
    return results


_BRAVE_SKIP = frozenset({
    "search.brave.com", "brave.com", "youtube.com", "www.youtube.com",
})


_YAHOO_HREF_RE = re.compile(r'href="(https?://[^"]+)"')
# The visible title lives in the <h3 class="title"> inside the result anchor. The
# anchor ALSO carries a breadcrumb ("Wikipedia" + "https://en.wikipedia.org > wiki
# > Sam_Altman"), so cleaning the whole anchor glues that junk onto the front of
# the title ("> Sam_AltmanSam Altman - Wikipedia").
_YAHOO_TITLE_RE = re.compile(
    r'<h3[^>]*class="[^"]*\btitle\b[^"]*"[^>]*>(.*?)</h3>', re.DOTALL,
)
_YAHOO_SNIPPET_RE = re.compile(r'class="compText[^"]*"[^>]*>(.*?)</div>', re.DOTALL)
# Yahoo injects an AI-summary card whose body is boilerplate, not an answer.
_YAHOO_JUNK_SNIPPET_MARKERS = ("summary generated by yahoo scout",)


def _is_junk_snippet(text: str) -> bool:
    low = text.lower()
    return not text or any(marker in low for marker in _YAHOO_JUNK_SNIPPET_MARKERS)


def _yahoo_search(query: str, *, max_results: int, timeout_s: float) -> list[dict[str, str]]:
    params = urllib.parse.urlencode({"p": query})
    html = _fetch(
        f"https://search.yahoo.com/search?{params}", timeout_s=timeout_s,
    )

    results: list[dict[str, str]] = []
    seen: set[str] = set()

    # Parse one result at a time. Yahoo emits a `compTitle` block per result with the
    # matching `compText` snippet trailing it before the next block opens. Collecting
    # every title and every snippet into two flat lists and pairing them by index --
    # what this used to do -- silently attaches the wrong snippet to a title as soon
    # as any one result carries no snippet, which is how a cited source ends up
    # describing something it never said.
    for chunk in html.split('class="compTitle')[1:]:
        href_match = _YAHOO_HREF_RE.search(chunk)
        if not href_match:
            continue
        url = _resolve_yahoo_url(href_match.group(1))
        if not url:
            continue
        domain = _domain(url)
        if not domain or url in seen or domain in _YAHOO_SKIP:
            continue

        title_match = _YAHOO_TITLE_RE.search(chunk)
        if not title_match:
            continue
        title = _clean_yahoo_title(_clean(title_match.group(1)))
        if len(title) < 3 or title.lower() in ("ad", "advertisement", "sponsored"):
            continue

        snippet = ""
        snippet_match = _YAHOO_SNIPPET_RE.search(chunk)
        if snippet_match:
            candidate = _clean(snippet_match.group(1))
            if not _is_junk_snippet(candidate):
                snippet = candidate

        seen.add(url)
        results.append({"title": title, "url": url, "snippet": snippet[:300]})
        if len(results) >= max_results:
            break
    return results


_YAHOO_SKIP = frozenset({
    "search.yahoo.com", "yahoo.com", "help.yahoo.com",
    "bing.com", "www.bing.com",
    "youtube.com", "www.youtube.com",
})


def _clean_yahoo_title(title: str) -> str:
    """Strip the inline domain prefix Yahoo sometimes prepends to titles."""
    m = re.match(r'^[A-Za-z0-9.\-]+(?:https?://[^\s]+\s*›?\s*[^\s]*\s*)', title)
    if m:
        return title[m.end():].strip()
    m = re.match(r'^https?://[^\s]+\s*›?\s*[^\s]*\s*', title)
    if m:
        return title[m.end():].strip()
    return title


def _resolve_yahoo_url(raw: str) -> str:
    """Yahoo wraps result URLs in a redirect; extract the real target."""
    m = re.search(r"RU=([^/]+)", raw)
    if m:
        return urllib.parse.unquote(m.group(1))
    if raw.startswith("http") and "yahoo.com" not in raw and "bing.com" not in raw:
        return raw
    return ""


_TRANSIENT_HTTP_CODES = frozenset({429, 500, 502, 503, 504})


def _fetch(url: str, *, timeout_s: float, max_retries: int = 1) -> str:
    last_exc: Exception = RuntimeError("no attempts")
    for attempt in range(max_retries + 1):
        req = urllib.request.Request(
            url,
            headers={
                "User-Agent": _USER_AGENT,
                "Accept": "text/html,application/xhtml+xml",
                "Accept-Language": "en-US,en;q=0.9",
            },
        )
        try:
            # The ONE outbound door: veto is enforced and the attempt reported
            # into the owning turn's ledger BEFORE any socket opens.
            with open_remote(req, timeout=timeout_s) as resp:
                return resp.read().decode("utf-8", errors="ignore")
        except urllib.error.HTTPError as exc:
            last_exc = exc
            # 429 (Brave's rate limit) and 5xx (Yahoo intermittently answers
            # "HTTP Error 500: INKApi Error" for a query it serves fine a second
            # later) are transient -- one short backoff recovers most of them.
            # Anything else is a real refusal and retrying only burns budget.
            if exc.code in _TRANSIENT_HTTP_CODES and attempt < max_retries:
                time.sleep(1.5 * (attempt + 1))
                continue
            raise
        except Exception as exc:
            last_exc = exc
            if attempt < max_retries:
                time.sleep(1.0)
                continue
            raise
    raise last_exc


def _domain(url: str) -> str:
    try:
        netloc = urllib.parse.urlparse(url).netloc.lower()
        return netloc[4:] if netloc.startswith("www.") else netloc
    except Exception:
        return ""
