"""Trust anchors for signed update manifests — the publisher's PUBLIC Ed25519 keys.

Fail-closed root of the new self-update lane (the NIA-026 decision, applied on record by
the 2026-09-01 signed-atomic-update mission): when no publisher key is pinned, NOTHING is
offered or installed. There is no integrity-only mode here — a mirror that controls both
the artifact and its checksum controls the "verified" result too.

Keys are pinned by `key_id` so rotation is a first-class operation: pin the new id,
drop the old one, and every manifest still signed by the retired key stops verifying as
`unknown_signing_key` even though the signature itself is cryptographically valid.

Sources, in order: an explicit map (tests / embedding code), the environment override
`VOOL_UPDATE_PUBLISHER_KEYS="key_id:hex,key_id:hex"` (release staging), and
`config/release/trusted_publisher_keys.json` (the shipped pin; PUBLIC keys only — the
private half is generated by installer/gen_publisher_keypair.py and must never live in
this repository).
"""
from __future__ import annotations

import json
import os
import re
from pathlib import Path

_HEX64_RE = re.compile(r"^[0-9a-f]{64}$")
_ENV_VAR = "VOOL_UPDATE_PUBLISHER_KEYS"

DEFAULT_CONFIG_PATH = Path("config/release/trusted_publisher_keys.json")


class TrustedPublishers:
    """The set of publisher public keys this install trusts, by key id."""

    def __init__(self, pinned_keys: dict[str, str] | None = None):
        self._keys: dict[str, str] = {}
        for key_id, public_hex in (pinned_keys or {}).items():
            normalized_id = str(key_id or "").strip()
            normalized_key = str(public_hex or "").strip().lower()
            if not normalized_id or not _HEX64_RE.match(normalized_key):
                # A malformed pin is a release-engineering defect; refuse the key rather
                # than trust a half-configured anchor.
                continue
            self._keys[normalized_id] = normalized_key

    # -- construction ------------------------------------------------------- #

    @property
    def is_configured(self) -> bool:
        return bool(self._keys)

    def is_known_key(self, key_id: str) -> bool:
        return str(key_id or "").strip() in self._keys

    def public_key_hex(self, key_id: str) -> str:
        return self._keys.get(str(key_id or "").strip(), "")

    @property
    def key_ids(self) -> tuple[str, ...]:
        return tuple(sorted(self._keys))

    @classmethod
    def from_env(cls, env: dict[str, str] | None = None) -> TrustedPublishers:
        """Parse the env override. Malformed entries are dropped (never partially trusted)."""
        source = dict(os.environ) if env is None else env
        raw = str(source.get(_ENV_VAR) or "").strip()
        if not raw:
            return cls(pinned_keys={})
        pinned: dict[str, str] = {}
        for entry in raw.split(","):
            entry = entry.strip()
            if not entry:
                continue
            key_id, separator, public_hex = entry.partition(":")
            if not separator:
                continue
            pinned[key_id.strip()] = public_hex.strip()
        return cls(pinned_keys=pinned)

    @classmethod
    def load(cls, config_path: Path | str | None = None, *, env: dict[str, str] | None = None) -> TrustedPublishers:
        """The production trust set: env override wins over the shipped config pin; both
        empty ⇒ fail closed (is_configured False)."""
        from_env = cls.from_env(env=env)
        if from_env.is_configured:
            return from_env
        path = Path(config_path) if config_path is not None else DEFAULT_CONFIG_PATH
        if not path.is_absolute():
            path = Path(__file__).resolve().parents[2] / path
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            return cls(pinned_keys={})
        if not isinstance(data, dict):
            return cls(pinned_keys={})
        return cls(pinned_keys={str(k): v for k, v in data.items() if not str(k).startswith("_")})


__all__ = ["TrustedPublishers"]
