"""Resolve each Linux CI shard from the committed timing-evidence snapshot.

This is the ACTIVATION of what ops/shard_plan.py planned: the CI resolver step
(.github/workflows/ci.yml, "Resolve this shard's test files") partitions the
canonically collected Linux files with measured per-file durations instead of
file size. The measurement chain and its guarantees:

  * the snapshot (ops/shard_weights.json, schema ``vool.shard-weights.v1``) is
    COMMITTED REPO DATA, generated by ``ops/shard_plan.py --write-weights``
    from the timing artifacts of a green instrumented run and reviewed as a
    normal diff. Ordinary CI runs never download run artifacts and need no
    credentials to balance shards: nothing here expires;
  * the snapshot is DATA, never code: values are validated as finite numbers
    and keys as plain repo-relative paths. Nothing from the file is executed,
    interpolated into a command, or handed a credential;
  * coverage is exact-once by construction and re-checked: the assignment must
    cover every collected Linux file exactly once or the resolver refuses it;
  * files the snapshot does not measure (new tests) get the snapshot's EXPLICIT
    conservative fallback weight; snapshot entries for files no longer
    collected (deleted tests) are ignored -- stale evidence can never shrink
    the collected set;
  * invalid evidence (missing, corrupt, wrong schema, wrong platform family,
    malformed keys or values) does NOT skip tests and does NOT red the build:
    the resolver degrades to the DOCUMENTED DETERMINISTIC SAFE FALLBACK --
    the previous partition, size-descending round-robin, replicated from the
    same authority the planner uses -- and emits ``::warning::`` annotations
    so the degradation is visible in the run and its logs.

Determinism: every shard runner computes the same global assignment from the
same snapshot and the same collected set (LPT, ties by path then shard index),
then writes only its own slice -- the same pattern the round-robin resolver
always used.
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path, PurePosixPath
from typing import Any

if str(Path(__file__).resolve().parent.parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ops.shard_plan import (
    PlanningError,
    _assignment_is_exactly_one_each,
    current_assignment,
    plan_lpt,
)

#: Schema of the committed evidence snapshot this resolver consumes. Generated
#: by ``ops/shard_plan.py --write-weights``; see docs/CI_SHARD_TIMING.md.
WEIGHTS_SCHEMA = "vool.shard-weights.v1"

#: The committed snapshot path inside the repository (relative to repo root).
DEFAULT_SNAPSHOT_PATH = Path("ops") / "shard_weights.json"

#: Resolver modes, reported in the shard log line and asserted by contract
#: tests: the measured partition, or the documented deterministic fallback.
MODE_MEASURED = "duration-aware-lpt"
MODE_FALLBACK = "fallback-size-round-robin"


class ResolverError(Exception):
    """The evidence snapshot cannot be trusted; no measured plan is produced."""


@dataclass(frozen=True)
class WeightsSnapshot:
    """Validated view of the committed snapshot: pure data, nothing executable."""

    per_file: dict[str, float]
    fallback_seconds: float
    platform: str
    provenance: dict[str, Any]

    def seconds_for(self, path: str) -> float:
        return self.per_file.get(path, self.fallback_seconds)


@dataclass
class ShardResolution:
    """The outcome of resolving one shard: its files, how, and what to report."""

    shard: int
    shards: int
    files: list[str]
    mode: str
    #: None for the measured mode; the ResolverError reason for the fallback.
    reason: str | None = None
    #: Collected files the snapshot does not measure (ran on the fallback weight).
    unmeasured: list[str] = field(default_factory=list)
    #: Snapshot entries for files no longer collected (ignored, never coverage).
    stale: list[str] = field(default_factory=list)

    def warnings(self) -> list[str]:
        lines: list[str] = []
        if self.reason is not None:
            lines.append(
                f"shard resolver fell back to {MODE_FALLBACK}: {self.reason}"
            )
        if self.unmeasured:
            names = ", ".join(self.unmeasured[:5])
            more = f" (+{len(self.unmeasured) - 5} more)" if len(self.unmeasured) > 5 else ""
            lines.append(
                f"{len(self.unmeasured)} file(s) have no measured duration and use the "
                f"snapshot's conservative fallback weight: {names}{more}"
            )
        if self.stale:
            names = ", ".join(self.stale[:5])
            more = f" (+{len(self.stale) - 5} more)" if len(self.stale) > 5 else ""
            lines.append(
                f"{len(self.stale)} stale snapshot entr{'y is' if len(self.stale) == 1 else 'ies are'} "
                f"ignored (not collected anymore): {names}{more}"
            )
        return lines


def _is_plain_relative_path(key: str) -> bool:
    """True only for a normalized, repo-relative, forward-slash POSIX path.

    A snapshot is untrusted data: keys that could smuggle a traversal
    (``..``), an absolute path, a Windows separator, or a non-normalized form
    (``a//b``, trailing slash) invalidate the whole file rather than being
    selectively trusted.
    """

    if not key or "\\" in key or key != key.strip():
        return False
    parsed = PurePosixPath(key)
    return (
        not parsed.is_absolute()
        and ".." not in parsed.parts
        and parsed.as_posix() == key
        and not key.startswith("/")
    )


def load_weights_snapshot(path: Path, *, sys_platform: str) -> WeightsSnapshot:
    """Load and validate the committed snapshot; refuse anything untrusted.

    Every refusal is a ResolverError naming the file and the reason; the caller
    decides between red (planning tools) and the documented safe fallback (the
    CI resolver). A snapshot that loads here is pure validated data.
    """

    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except OSError as exc:
        raise ResolverError(f"timing-evidence snapshot unreadable ({path}): {exc}") from exc
    except json.JSONDecodeError as exc:
        raise ResolverError(f"timing-evidence snapshot is corrupt JSON ({path}): {exc}") from exc
    if not isinstance(payload, dict) or payload.get("schema") != WEIGHTS_SCHEMA:
        raise ResolverError(
            f"timing-evidence snapshot schema is not {WEIGHTS_SCHEMA} ({path})"
        )
    platform_name = payload.get("sys_platform")
    if not isinstance(platform_name, str) or not platform_name:
        raise ResolverError(f"timing-evidence snapshot has no platform identity ({path})")
    if platform_name != sys_platform:
        raise ResolverError(
            f"timing-evidence snapshot is for {platform_name!r}, not {sys_platform!r} ({path})"
        )
    fallback = payload.get("fallback_weight_seconds")
    if isinstance(fallback, bool) or not isinstance(fallback, (int, float)):
        raise ResolverError(
            f"timing-evidence snapshot has no explicit fallback weight ({path})"
        )
    fallback_seconds = float(fallback)
    if not math.isfinite(fallback_seconds) or fallback_seconds <= 0:
        raise ResolverError(
            f"timing-evidence snapshot fallback weight must be positive and finite, "
            f"got {fallback!r} ({path})"
        )
    raw_weights = payload.get("weights")
    if not isinstance(raw_weights, dict) or not raw_weights:
        raise ResolverError(f"timing-evidence snapshot carries no per-file weights ({path})")
    per_file: dict[str, float] = {}
    for key, value in raw_weights.items():
        if not isinstance(key, str) or not _is_plain_relative_path(key):
            raise ResolverError(
                f"timing-evidence snapshot key is not a plain repo-relative path: {key!r} ({path})"
            )
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise ResolverError(
                f"timing-evidence snapshot weight for {key} is not a number: {value!r} ({path})"
            )
        seconds = float(value)
        # Zero is a legitimate measured duration (a very fast file); anything
        # negative or non-finite is corrupt data, never "zero-cost" coverage.
        if not math.isfinite(seconds) or seconds < 0:
            raise ResolverError(
                f"timing-evidence snapshot weight for {key} is not a valid duration: {value!r} ({path})"
            )
        per_file[key] = seconds
    provenance = payload.get("provenance")
    if provenance is not None and not isinstance(provenance, dict):
        raise ResolverError(f"timing-evidence snapshot provenance is not an object ({path})")
    return WeightsSnapshot(
        per_file=per_file,
        fallback_seconds=fallback_seconds,
        platform=platform_name,
        provenance=dict(provenance or {}),
    )


def assign_duration_aware(
    files: Sequence[str], snapshot: WeightsSnapshot, *, shards: int
) -> tuple[tuple[str, ...], ...]:
    """Deterministic LPT assignment over measured weights; exact-once or refuse.

    Files the snapshot does not measure run on the snapshot's explicit
    fallback weight, so an unmeasured file is never treated as free.
    """

    weights = {target: snapshot.seconds_for(target) for target in files}
    assignment = plan_lpt(weights, shards=shards)
    problem = _assignment_is_exactly_one_each(assignment, files)
    if problem:
        raise ResolverError(f"duration-aware assignment is not complete ({problem})")
    return assignment


def resolve_shard(
    files: Sequence[str],
    *,
    shard: int,
    shards: int,
    snapshot_path: Path,
    repo_root: Path,
    sys_platform: str | None = None,
) -> ShardResolution:
    """Resolve ONE shard's file list from the committed snapshot.

    Measured evidence produces the duration-aware LPT partition. Any
    ResolverError degrades to the documented deterministic safe fallback --
    the previous size round-robin -- with the reason carried as a warning.
    Both paths return a complete slice of a complete partition.
    """

    if not 0 <= shard < shards:
        raise ResolverError(f"shard index {shard} out of range 0..{shards - 1}")
    platform_name = sys_platform if sys_platform is not None else sys.platform
    unique_files = sorted(set(files))
    if len(unique_files) != len(files):
        raise ResolverError("collected file list contains duplicates")
    try:
        snapshot = load_weights_snapshot(snapshot_path, sys_platform=platform_name)
        assignment = assign_duration_aware(unique_files, snapshot, shards=shards)
        measured = set(snapshot.per_file)
        collected = set(unique_files)
        return ShardResolution(
            shard=shard,
            shards=shards,
            files=list(assignment[shard]),
            mode=MODE_MEASURED,
            unmeasured=sorted(collected - measured),
            stale=sorted(measured - collected),
        )
    except ResolverError as exc:
        try:
            fallback = current_assignment(unique_files, repo_root=repo_root, shards=shards)
        except PlanningError as fallback_exc:
            raise ResolverError(
                f"safe fallback partition failed after evidence error ({exc}): {fallback_exc}"
            ) from fallback_exc
        problem = _assignment_is_exactly_one_each(fallback, unique_files)
        if problem:
            raise ResolverError(f"safe fallback assignment is not complete ({problem})")
        return ShardResolution(
            shard=shard,
            shards=shards,
            files=list(fallback[shard]),
            mode=MODE_FALLBACK,
            reason=str(exc),
        )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Resolve one Linux CI shard from the committed timing-evidence snapshot."
    )
    parser.add_argument("--shard", type=int, required=True)
    parser.add_argument("--shards", type=int, default=10)
    parser.add_argument(
        "--files", type=Path, required=True,
        help="Newline-separated canonically collected Linux test files (macOS routing already applied).",
    )
    parser.add_argument(
        "--weights", type=Path, default=DEFAULT_SNAPSHOT_PATH,
        help=f"Committed evidence snapshot (default: {DEFAULT_SNAPSHOT_PATH}).",
    )
    parser.add_argument("--repo-root", type=Path, default=Path("."))
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument(
        "--platform", default=sys.platform,
        help="Platform family the snapshot must be measured on (default: this system's sys.platform).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        files = [
            line
            for line in args.files.read_text(encoding="utf-8").splitlines()
            if line.strip()
        ]
    except OSError as exc:
        print(f"!! collected file list unreadable ({args.files}): {exc}", file=sys.stderr)
        return 1
    try:
        resolution = resolve_shard(
            files,
            shard=args.shard,
            shards=args.shards,
            snapshot_path=args.weights,
            repo_root=args.repo_root,
            sys_platform=args.platform,
        )
    except ResolverError as exc:
        print(f"!! {exc}", file=sys.stderr)
        return 1
    for warning in resolution.warnings():
        print(f"::warning::{warning}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(resolution.files) + "\n", encoding="utf-8")
    print(
        f"shard {resolution.shard}/{resolution.shards}: {len(resolution.files)} of "
        f"{len(files)} files [{resolution.mode}]"
    )
    if not resolution.files:
        print(f"!! shard {resolution.shard} resolved empty — partitioning bug", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
