"""The shared localization registry: load locales, fallback chain, missing policy.

Registry layout (JSON per locale, one canonical source locale):

    registry/en.json         source of truth for every string
    registry/pt-BR.json      GENERATED translation (labeled, unreviewed)
    registry/qya-pseudo.json pseudo-locale, generated by tools, never shipped
    registry/ar-TORTURE.json RTL stress fixture, synthetic by design

Fallback chain for a lookup in ``pt-BR``:
    exact tag -> language-only ('pt') -> default ('en') -> MISSING marker.

Missing-string policy is visible-by-default: a missing key renders as
``[missing: <key> (locale)]`` and is recorded so audits fail loudly instead of
silently leaking English into localized builds.
"""
from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path

from vool_localization import formatting, message, plural

MISSING_PATTERN = "[missing: {key} ({lang})]"
GENERATED_NOTE_KEY = "__generated_note"


@dataclass
class LocaleMeta:
    locale: str
    label: str = ""
    generated: bool = False
    human_reviewed: bool = False


@dataclass
class Catalog:
    strings: dict[str, dict[str, str]] = field(default_factory=dict)   # locale -> key -> template
    metas: dict[str, LocaleMeta] = field(default_factory=dict)
    default_locale: str = "en"
    missing: list[tuple[str, str]] = field(default_factory=list)       # (locale, key)
    strict: bool = False

    # ---- loading -------------------------------------------------------
    @classmethod
    def load(cls, registry_dir: Path | None = None, *, default_locale: str = "en",
             strict: bool = False) -> "Catalog":
        if registry_dir is None:
            registry_dir = Path(__file__).resolve().parent.parent / "registry"
        cat = cls(default_locale=default_locale, strict=strict)
        for path in sorted(registry_dir.glob("*.json")):
            data = json.loads(path.read_text(encoding="utf-8"))
            meta = data.get("_meta", {})
            locale = meta.get("locale") or path.stem
            cat.metas[locale] = LocaleMeta(
                locale=locale,
                label=meta.get("label", ""),
                generated=bool(meta.get("generated", False)),
                human_reviewed=bool(meta.get("human_reviewed", False)),
            )
            cat.strings[locale] = {k: v for k, v in data.get("strings", {}).items()}
        if default_locale not in cat.strings:
            raise ValueError(f"default locale {default_locale!r} missing from registry")
        return cat

    def chain(self, locale: str) -> list[str]:
        tag = locale.strip().replace("_", "-")
        lang = tag.split("-", 1)[0]
        chain: list[str] = []
        for candidate in (tag, lang, self.default_locale):
            if candidate in self.strings and candidate not in chain:
                chain.append(candidate)
        return chain

    # ---- lookup --------------------------------------------------------
    def t(self, key: str, locale: str | None = None, **args) -> str:
        """Translate + format. Returns visible MISSING marker when unresolved."""
        loc = locale or self.default_locale
        for candidate in self.chain(loc):
            template = self.strings[candidate].get(key)
            if template is not None:
                rule = plural.resolve_rule(candidate)
                return message.format_message(
                    template, args,
                    plural_category=lambda n, _r=rule: _r(n),
                    format_number=lambda v, _loc=candidate: formatting.format_number(v, _loc),
                )
        self.missing.append((loc, key))
        if self.strict:
            raise KeyError(f"missing string {key!r} for locale {loc!r}")
        return MISSING_PATTERN.format(key=key, lang=loc)

    def exists(self, key: str, locale: str | None = None) -> bool:
        loc = locale or self.default_locale
        return any(key in self.strings[c] for c in self.chain(loc))

    def origin(self, key: str, locale: str) -> str | None:
        """Which locale in the chain actually served this key."""
        for candidate in self.chain(locale):
            if key in self.strings[candidate]:
                return candidate
        return None

    def keys(self) -> set[str]:
        return set(self.strings[self.default_locale])

    # ---- convenience formatting -----------------------------------------
    def number(self, value: float, locale: str, decimals: int | None = None) -> str:
        return formatting.format_number(value, locale, decimals)

    def currency(self, amount: float, code: str, locale: str) -> str:
        return formatting.format_currency(amount, code, locale)

    def date(self, dt, locale: str, kind: str = "date") -> str:
        return formatting.format_date(dt, locale, kind)

    def direction(self, locale: str) -> str:
        return "rtl" if locale.lower().startswith(("ar", "he", "fa", "ur")) else "ltr"
