"""Generate a build's files with the model the operator actually selected.

`build_ollama_generate_fn` in this package posts straight to Ollama's `/api/chat` with the LOCAL
runtime tag. That is correct when nothing is pinned and wrong the moment it is: every file a build
writes would be generated by `qwen3:8b` while the turn is attributed to whatever the operator chose
in the composer. Because that swap is unacceptable, `_should_run_builder_controller` refused a pinned
turn outright -- and the measured outcome was worse than the disease. The turn fell through to the
selected model's tool loop, the model did not call `workspace.write_file`, and

    i need <ws>/v5/median.py with a median function

came back "I couldn't map that cleanly to a real action" after 75.6s. Pinning a model meant you
could not build at all.

This module closes the gap from the other side: the builder's one model dependency is
``generate_fn(prompt) -> str``, so a pinned turn gets a generate_fn backed by the SELECTED provider
instead of the local tag. It deliberately routes through ``MemoryFirstRouter._invoke_manifest``
rather than posting to an adapter directly, because that seam is where the runtime keeps the things
a 65-generation loop must not bypass:

* the paid-cloud authorization gate (a build must never quietly spend the operator's key 65 times),
* the provider circuit breaker,
* `model.call_started` / `.call_completed` / `.call_failed` carrying the REAL provider and model id.

When the pin cannot be honoured -- unknown model id, unhealthy provider, or a paid model with no
spend authorization -- nothing is silently substituted. The caller is handed a refusal that names
the model and the reason and offers the local lane, which is a usable answer; the generic
"I couldn't map that cleanly to a real action" is not.
"""
from __future__ import annotations

import time
from collections.abc import Callable
from typing import Any

from core.agent_runtime.turn_frontdoor import explicit_model_owns_semantic_turn

# A build issues up to 65 sequential generations. Each one gets its own slice of the shared
# `BuilderGenerationBudget`; this only bounds a single call so one wedged provider cannot eat the
# whole ceiling in one request.
_PINNED_CALL_TIMEOUT_SECONDS = 300.0
_PINNED_NUM_PREDICT = 6144

# Room a reasoning model needs BEFORE its artifact starts, mirroring the shared thinking reserve
# (`core.output_budget_policy`): when a provider mandates reasoning, the monologue and the file
# share one output ceiling, and a ceiling sized for the file alone comes back empty.
_PINNED_REASONING_RESERVE_TOKENS = 2048

#: Both markers, verbatim from the provider's own typed 400 body on the OpenRouter lane
#: ("Reasoning is mandatory for this endpoint and cannot be disabled."). Grounded in the
#: provider's error, not a model-name guess.
_REASONING_MANDATORY_MARKERS = ("reasoning is mandatory", "cannot be disabled")


def _reasoning_mandatory_refusal(error_text: Any, manifest: Any = None) -> bool:
    """Whether a generation failure is the provider refusing our reasoning-disabled request
    policy for an endpoint that mandates reasoning. The provider's own error says so."""
    lowered = str(error_text or "").lower()
    matched = all(marker in lowered for marker in _REASONING_MANDATORY_MARKERS)
    if matched and manifest is not None:
        # Terminal fact: this endpoint's model reasons. Record it so later sizings and the
        # invoke loop's widened-retry read a fact the provider itself reported.
        try:
            from core.output_budget_policy import note_observed_reasoning

            note_observed_reasoning(
                str(getattr(manifest, "provider_id", "") or ""),
                str(getattr(manifest, "model_name", "") or ""),
            )
        except Exception:
            pass
    return matched


def requested_model_id(source_context: dict[str, Any] | None) -> str:
    """The concrete model the operator pinned for this turn, or '' when they pinned nothing."""
    if not explicit_model_owns_semantic_turn(source_context):
        return ""
    return str((source_context or {}).get("requested_model") or "").strip()


def resolve_pinned_manifest(agent: Any, source_context: dict[str, Any] | None) -> Any | None:
    """The provider manifest for the pinned model, or None when it resolves to nothing."""
    requested = requested_model_id(source_context)
    if not requested:
        return None
    router = getattr(agent, "memory_router", None)
    if router is None:
        return None
    try:
        return router._requested_model_manifest(dict(source_context or {}))
    except Exception:
        return None


#: The stable lead of `pinned_build_refusal`'s output. Part of the runtime's typed-refusal
#: family (`core.grounding_publication.is_typed_refusal_text`): a deterministic refusal is the
#: runtime's own statement of what it declined and why -- including a quoted provider error --
#: not a model's attestation claim, and the evidence binder must not rewrite it.
PINNED_BUILD_REFUSAL_LEAD = "I can't build with"


def pinned_build_refusal(
    *,
    requested_model: str,
    reason: str,
    workspace_hint: str = "",
) -> str:
    """What the operator is told when their pinned model cannot generate this build.

    Names the model, names the reason, and offers the one action that works. A build refusal is
    allowed to be a refusal; it is not allowed to be "I couldn't map that cleanly to a real action",
    which tells the operator nothing and hides that a model choice caused it.

    ``workspace_hint`` names the destination only when it is RELATIVE to the workspace root. The
    absolute profile path behind it stays off the chat copy -- it is a personal machine path, and
    the turn's audit record already carries it for inspection.
    """
    lines = [
        f"I can't build with `{requested_model}` on this turn: {reason}.",
        "",
        "I won't generate the files with a different model than the one you selected and report it "
        "as yours.",
        "",
        "Two ways forward:",
        "- Switch the model picker back to `vool` (auto) and repeat the request — the local build "
        "lane writes and verifies the files itself.",
        "- Or pin a model this machine can actually reach for generation and repeat the request.",
    ]
    shown = str(workspace_hint or "").strip().strip("/")
    if shown and "/" not in shown and ".." not in shown:
        lines.append("")
        lines.append(f"Nothing was written. Workspace folder: `{shown}`.")
    else:
        lines.append("")
        lines.append("Nothing was written.")
    return "\n".join(lines)


# The prefix `build_pinned_generate_fn` stamps on `BuilderGenerationBudget.last_error` when the
# PAID-CALL AUTHORITY refused the generation before any request was sent. The builder controller
# reads it back to say "the provider was not contacted" instead of "the model produced nothing",
# which is the difference between an authorization refusal and a provider failure.
AUTHORIZATION_REFUSED_PREFIX = "paid call not authorized:"


def pinned_failure_reason(budget: Any) -> str:
    """The accurate cause phrase for a pinned build whose files never appeared.

    ``budget.last_error`` is the builder's only channel from its generations, and "the paid-call
    authorization was refused" and "the provider returned nothing" must not read as one another:
    the first says no request was ever sent, the second says one was.
    """
    last_error = str(getattr(budget, "last_error", "") or "")
    if last_error.startswith(AUTHORIZATION_REFUSED_PREFIX):
        code = last_error[len(AUTHORIZATION_REFUSED_PREFIX) :].strip() or "not_authorized_or_reserved"
        return (
            f"the paid-call authorization for this build was refused ({code}), so the provider "
            "was not contacted"
        )
    return f"it returned nothing usable for this build ({last_error or 'empty response'})"


def _manifest_needs_paid_reservation(manifest: Any) -> bool:
    """Whether dispatching this pinned manifest crosses ``_invoke_manifest``'s paid gate.

    The gate's own classifier stays the authority; this pre-check only decides whether a
    reservation must be made BEFORE the call, so a manifest it cannot classify is left to refuse
    there exactly as before rather than being re-classified here.
    """
    try:
        from core.model_selection_policy import is_verified_free_cloud_manifest, provider_cost_class

        return (
            provider_cost_class(manifest) == "paid_cloud"
            and not is_verified_free_cloud_manifest(manifest)
        )
    except Exception:
        return False


def build_pinned_generate_fn(
    agent: Any,
    *,
    manifest: Any,
    task: Any,
    source_context: dict[str, Any] | None,
    budget: Any,
) -> Callable[[str], str]:
    """One text generation on the OPERATOR'S model: prompt in, the model's answer out.

    Mirrors ``build_ollama_generate_fn``'s contract exactly -- same signature, same budget
    accounting, same "empty string means this call produced nothing" convention -- so the builder
    itself does not know or care which lane it is on.

    A paid pinned manifest is dispatched ONLY under a reservation from the same authority the
    router's own pick lane uses (``reserve_owner_pick_paid_call``). The builder used to arrive at
    ``_invoke_manifest`` with no ``authorized_paid_call`` in its context, so every generation of
    every pinned paid build refused with ``paid_call_not_authorized_or_reserved`` before any
    request was sent. Each generation now reserves its own call and the invoke loop settles or
    releases it, so a multi-generation build stays inside the per-task/daily/monthly caps and a
    refused reservation is named to the operator instead of reading as a provider failure.
    """
    from adapters.base_adapter import ModelRequest
    from core.agent_runtime.builder import app_builder
    from core.paid_call_reservation import release_owner_pick_paid_call, reserve_owner_pick_paid_call

    ctx = dict(source_context or {})
    router = agent.memory_router
    provider_id = str(getattr(manifest, "provider_id", "") or "")
    model_id = str(getattr(manifest, "model_name", "") or "")
    needs_reservation = _manifest_needs_paid_reservation(manifest)
    # LEARNED WITHIN THE BUILD: once this lane's provider has refused our reasoning-disabled
    # artifact policy with its own typed 400, every LATER generation asks reasoning-permitted
    # directly. Re-attempting the refused policy per generation doubled every call and burned
    # the build's wall clock on doomed round trips (measured live 2026-09-17: generations
    # 1..9 each paid the 400 before their retry, and the build ran out of time mid-file).
    provider_mandates_reasoning = {"yes": False}

    def generate_fn(prompt: str) -> str:
        if budget.exhausted():
            budget.exhausted_reason = (
                f"builder wall-clock budget of {budget.total_seconds:.0f}s spent after "
                f"{budget.calls} generation(s)"
            )
            return ""
        if provider_mandates_reasoning["yes"]:
            return _generate_with_reasoning_permitted(prompt, time.monotonic())
        authorization = None
        call_ctx = ctx
        generation_subtask = f"builder_generation_{budget.calls + 1}"
        if needs_reservation:
            denial: dict[str, str] = {}
            authorization = reserve_owner_pick_paid_call(
                manifest=manifest,
                task=task,
                # The per-generation subtask rides the RESERVATION's own context: the
                # orchestration run store keys runs UNIQUE(task_id, turn_id, subtask_id), and
                # one shared subtask made every reservation after the first collide (measured:
                # reservation_unavailable via UNIQUE constraint), so a multi-generation paid
                # build died on its second file and the reasoning re-ask died the same way.
                source_context={**ctx, "subtask_id": generation_subtask},
                task_kind="code_complex",
                call_role="answer_generation",
                denial=denial,
            )
            if authorization is None:
                # The monetary authority refused before anything was sent. The code it named is
                # the operator's actionable fact ("daily_spend_cap_exceeded"), so it rides the
                # budget's error channel under the prefix the controller phrases from.
                budget.last_error = (
                    f"{AUTHORIZATION_REFUSED_PREFIX} {denial.get('reason') or 'not_authorized_or_reserved'}"
                )
                return ""
            call_ctx = {
                **ctx,
                "authorized_paid_call": authorization,
                "model_call_role": "answer_generation",
                "subtask_id": generation_subtask,
            }
        budget.calls += 1
        started = time.monotonic()
        request = ModelRequest(
            task_kind="code_complex",
            prompt=prompt,
            system_prompt=(
                "You are generating source files for a build. Answer with the requested content "
                "only. No preamble, no commentary."
            ),
            temperature=0.2,
            max_output_tokens=_PINNED_NUM_PREDICT,
            # `messages` is deliberately LEFT EMPTY so the adapter builds them from
            # `system_prompt` + `prompt`. Handing it a pre-built `[{"role": "user", ...}]` looks
            # equivalent and is not: `core/prompt_budget.py` refuses any prompt whose protected
            # system instructions are absent from the message list, and a caller-supplied list
            # without a system message fails that check no matter how small the prompt is. Measured
            # live on the daemon at 12:06:53 — `prompt_budget_exceeded: protected system prompt and
            # current turn require 166 tokens, but only 16384 are available`, with
            # `system_prompt_preserved: false`. 166 of 16384 is not a size problem; the shape was
            # wrong, and every generation of the build failed on it.
            output_mode="plain_text",
            # A build generation is a bounded ARTIFACT call: the answer is a file's contents, and a
            # reasoning model that spends this budget on chain-of-thought returns nothing to write.
            # Measured on the incident turn: 8,192 tokens of reasoning, no artifact, and the
            # operator was then told the model was unreachable. Declared as request policy rather
            # than as another task-name metadata flag (AGENT_HANDOVER §1A rule 8), so the adapter
            # translates one contract instead of learning every caller's name for itself.
            reasoning_mode="disabled",
            metadata={"builder_generation": True},
        )
        try:
            _adapter, response, error = router._invoke_manifest(
                manifest=manifest,
                request=request,
                output_mode="plain_text",
                task=task,
                source_context=call_ctx,
            )
        except Exception as exc:  # a provider fault must not take the whole build down
            budget.seconds_spent += time.monotonic() - started
            if _reasoning_mandatory_refusal(exc, manifest):
                provider_mandates_reasoning["yes"] = True
                if authorization is not None:
                    # The exception escaped the invoke loop, so this reservation is still
                    # standing; hand it back before the re-ask takes a fresh one.
                    release_owner_pick_paid_call(
                        authorization,
                        reason="call_failed",
                        source_context=ctx,
                        call_role="answer_generation",
                    )
                return _generate_with_reasoning_permitted(prompt, started)
            budget.last_error = type(exc).__name__  # type: ignore[attr-defined]
            if authorization is not None:
                # The invoke loop terminalizes a reservation it handled itself; an exception that
                # ESCAPED it leaves the reservation standing. The request's dispatch state is
                # unknown from here, so "call_failed" -- the reason that assumes it may have been
                # served and billed -- is the conservative release.
                release_owner_pick_paid_call(
                    authorization,
                    reason="call_failed",
                    source_context=ctx,
                    call_role="answer_generation",
                )
            return ""
        budget.seconds_spent += time.monotonic() - started
        if error or response is None:
            if _reasoning_mandatory_refusal(error, manifest):
                provider_mandates_reasoning["yes"] = True
                # The provider refused our reasoning-disabled policy for an endpoint that
                # mandates reasoning (its own typed 400 says so). The artifact preference stands,
                # but it cannot override the endpoint: re-ask the SAME generation once with
                # reasoning permitted and a ceiling widened by the reasoning reserve, then strip
                # the monologue as always. Measured 2026-09-17: every generation of a pinned
                # `z-ai/glm-5.3-flash` build 400'd with "Reasoning is mandatory for this endpoint
                # and cannot be disabled" and the build refused -- the disabled policy is a
                # preference, not a hill the build should die on.
                return _generate_with_reasoning_permitted(prompt, started)
            budget.last_error = str(error or "no_response")  # type: ignore[attr-defined]
            return ""
        # `strip_reasoning_monologue` for the same reason the local lane does it: a thinking model's
        # monologue is not an answer and must never be written into a file.
        return app_builder.strip_reasoning_monologue(str(getattr(response, "output_text", "") or ""))

    def _generate_with_reasoning_permitted(prompt: str, started: float) -> str:
        """The one bounded re-ask when the endpoint mandates reasoning.

        Same generation, same reservation flow (a fresh reservation for a paid lane), reasoning
        left at the lane's default instead of disabled, and the ceiling widened by the reasoning
        reserve so the monologue and the artifact both fit. The re-ask is RECORDED, not silent:
        a `model.call_retrying` row names the policy change on the operator's event stream, and
        `budget.calls` counts it like any other attempt.
        """
        try:
            from core.runtime_task_events import emit_runtime_event

            emit_runtime_event(
                ctx,
                event_type="model.call_retrying",
                message=(
                    "Provider mandates reasoning for this endpoint; re-asking the generation with "
                    "reasoning permitted and a widened output ceiling."
                ),
                provider_id=provider_id,
                model_id=model_id,
                retry_policy="pinned_reasoning_permitted",
            )
        except Exception:
            pass
        authorization = None
        retry_subtask = f"builder_generation_retry_{budget.calls + 1}"
        retry_ctx = ctx
        if needs_reservation:
            denial: dict[str, str] = {}
            authorization = reserve_owner_pick_paid_call(
                manifest=manifest,
                task=task,
                # Distinct from the first attempt's subtask: the orchestration run store is
                # UNIQUE(task_id, turn_id, subtask_id), and the re-ask must own its own row.
                source_context={**ctx, "subtask_id": retry_subtask},
                task_kind="code_complex",
                call_role="answer_generation",
                denial=denial,
            )
            if authorization is None:
                budget.last_error = (
                    f"{AUTHORIZATION_REFUSED_PREFIX} {denial.get('reason') or 'not_authorized_or_reserved'}"
                )
                return ""
            retry_ctx = {
                **ctx,
                "authorized_paid_call": authorization,
                "model_call_role": "answer_generation",
                "subtask_id": retry_subtask,
            }
        budget.calls += 1
        request = ModelRequest(
            task_kind="code_complex",
            prompt=prompt,
            system_prompt=(
                "You are generating source files for a build. Answer with the requested content "
                "only. No preamble, no commentary."
            ),
            temperature=0.2,
            max_output_tokens=_PINNED_NUM_PREDICT + _PINNED_REASONING_RESERVE_TOKENS,
            output_mode="plain_text",
            # Reasoning left at the lane's default: the endpoint refused to disable it. The
            # monologue is stripped from the artifact below, as on every other lane.
            metadata={"builder_generation": True, "reasoning_mandated_by_provider": True},
        )
        try:
            _adapter, response, error = router._invoke_manifest(
                manifest=manifest,
                request=request,
                output_mode="plain_text",
                task=task,
                source_context=retry_ctx,
            )
        except Exception as exc:
            budget.seconds_spent += time.monotonic() - started
            budget.last_error = type(exc).__name__  # type: ignore[attr-defined]
            if authorization is not None:
                release_owner_pick_paid_call(
                    authorization,
                    reason="call_failed",
                    source_context=ctx,
                    call_role="answer_generation",
                )
            return ""
        budget.seconds_spent += time.monotonic() - started
        if error or response is None:
            budget.last_error = str(error or "no_response")  # type: ignore[attr-defined]
            return ""
        return app_builder.strip_reasoning_monologue(str(getattr(response, "output_text", "") or ""))

    generate_fn.budget = budget  # type: ignore[attr-defined]
    generate_fn.provider_id = provider_id  # type: ignore[attr-defined]
    generate_fn.model_id = model_id  # type: ignore[attr-defined]
    return generate_fn


def pinned_build_attribution(*, requested_model: str, provider_id: str, model_id: str) -> str:
    """The line appended to a pinned build's report, so attribution is stated rather than assumed."""
    shown = model_id or requested_model
    if provider_id and provider_id != shown:
        return f"Files generated by `{shown}` (provider `{provider_id}`), the model you selected."
    return f"Files generated by `{shown}`, the model you selected."
